### ISSUE TITLE
PreDB thoughts...

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#108]
So, because pretty much no preDB's have api's, we are going to need to screen scrape. My thoughts were to scrape multiple sites, this spreads out the chance of having just 1 changing its HTML and causing things to break. We could try focus on sites that return name and potentially size? Would allow us to do some checking, if release is say within x% of preDB size?

Another option would be to scrape and use something like heroku to turn it into an api. Downside I guess is that if traffic were to pickup it would start to cost :(

I started writing some scraping code already (using beautifulsoup), only 1 site done though...

Thoughts? Would this be worthwhile? What should the pre checker class return? Just a boolean if the release exists and maybe size? You could use this to determine some type of metric on how sure we are its a real release? That way cleaning scripts could be made to remove dead wood (maybe I'm over thinking this...)

**Comment by Murodese** [comment]
You could also parse http://predb.me/, as mentioned by somebody :)

**Comment by brookesy2** [comment]
Yeah, for something like that though we may be better off hitting it with
each pre request. The bummer is the RSS is horrible. I have a whole list of
sites I could potentially scrape.

Begs the question though, should we just send individual queries on
releases we can't find (iv done one for orlydb already) or should we setup
polling to try save every release.

Could use IRC for the steady stream and some pre sites to hit for any not
found locally?

Thoughts?

**Comment by Murodese** [comment]
Yeah, not sure. It depends on whether you want to match every release to a pre entry (which doesn't really gain us much) or just the ones that can't be renamed. If there's a db of some sort that you can just query with an md5 and get back a name, that'd be perfect. Not sure it exists though.

**Comment by brookesy2** [comment]
I don't think it does :( I suppose we could md5 names as we add them to the
pre table?

I'd say if we can't find it in local, hit some sites and see what turns up,
if nothing, give up :)
