### ISSUE TITLE
length field in RSS

### ISSUE THREAD

**Issue by xsivart** [Murodese/pynab#111]
A friend was using nzbmegasearch and it was never returning results properly against pynab.  After adding some code to megasearch's scripts I was able to make it display results but it was more of a work around.

The issue with those scripts was that the RSS for pynab is returning **length="None"** and nzbmegasearch didn't have error handling for that.

Example from the RSS feed (Right Click -> View Source)
```
            <group>alt.binaries.multimedia</group>
            <enclosure url="https://xxxx/api?t=g&amp;guid=235500&amp;apikey=xxxx" length="None" type="application/x-nzb"></enclosure>
            <grabs>0</grabs>
```
This doesn't happen for all results but some/most of the recent content indexed (last ~400 days) doesn't have a "length" value associated with it.

If I pick something older it has a length value associated with it:
```
            <group>alt.binaries.movies.divx</group>
            <enclosure url="https://xxxx/api?t=g&amp;guid=267076&amp;apikey=xxxx" length="823353769" type="application/x-nzb"></enclosure>
            <grabs>0</grabs>
```

The download itself works perfectly fine for the 'length="None"' results but I'm just wondering how the length is calculated and if maybe something is broken.

Enjoy your holiday :)

**Comment by Murodese** [comment]
Works for me. Do you update using update.sh? If not, run `alembic upgrade head `. Size should never be None (should be 0 if there's a problem with getting size). Can you check the db rows in the releases table for those releases and paste what's in size for those?

**Comment by xsivart** [comment]
Yep, I had been running updates as well as `alembic upgrade head`.

Here is the info from the table, it looks like size is just blank for the broken release:
```
pynab=> select id,size from releases where id='235500';
   id   | size 
--------+------
 235500 |     
(1 row)
```

```
pynab=> select id,size from releases where id='267076';
   id   |   size    
--------+-----------
 267076 | 823353769
(1 row)
```

**Comment by Murodese** [comment]
Can you paste the passworded status for those as well? Wondering if the size checking in rar postproc isn't working properly.

**Comment by xsivart** [comment]
Sure thing!

```
pynab=> select id,size,passworded from releases where id='267076';
   id   |   size    | passworded 
--------+-----------+------------
 267076 | 823353769 | NO
(1 row)

pynab=> select id,size,passworded from releases where id='235500';
   id   | size | passworded 
--------+------+------------
 235500 |      | NO
(1 row)
```

**Comment by xsivart** [comment]
As an unreleated note, I had to roll back I'm guessing due to the nntplib upgrade commit.  Something is not properly closing the connections and I was starting to get tons of maximum connections reached errors and I could see hundreds of connections to my provider in netstat. As soon as I rolled back the maximum connections errors stopped.

**Comment by Murodese** [comment]
Yeah, pretty sure I know what's causing it. I can fix the releases retroactively, but it'll have to wait until I get back - about a week. Does it happen with most new releases, or just a few? Run this select for me as well:

`select count(*) from releases where size is null and passworded = "UNKNOWN";`

**Comment by Murodese** [comment]
Yeah that's from #109. See ukharley's comment for a temp fix.

**Comment by xsivart** [comment]
I've noticed there were no sizes associated with the releases in the RSS feed in the past and just ignored it.  Just recently started looking into the issue with nzbmegasearch but based off of the queries I'm guessing it's been happening for awhile:

```
pynab=> select count(*) from releases where size is null and passworded='UNKNOWN';
  count  
---------
 1595623
```

And just to have the opposite of that...
```
pynab=> select count(*) from releases where size is not null and passworded='UNKNOWN';
 count 
-------
 74094
```

**Comment by Murodese** [comment]
Try another permutation:

`select count(*) from releases where size is null and passworded='NO';`

**Comment by Murodese** [comment]
I just wrote up a long post and then realised something simple: are these releases all older than a certain age, from before late August 2014? That's when size-checking changed and everything from before then would be null. If it's happening for new releases, that's a problem - but it's expected of releases older than that.

To fix the old releases is easy:

`python3 scripts/fill_sizes_from_nzb.py`

**Comment by xsivart** [comment]
```
pynab=> select count(*) from releases where size is null and passworded='NO';
 count
--------
 556202
(1 row)
```

I think most of the releases with the missing size are from before that time.  I'm running that script now and it looks like it is fixing quite a few according to the output. It'll probably be awhile but it is done but I'll see how things look after that.

I checked some recent results in the normal indexer RSS feed (t=tvsearch&cat=5040%2C5030) and it looks like all of them have length's.  Sorry for the more than likely false alarm :)

**Comment by Murodese** [comment]
My fault, should've bound it into an alembic upgrade so it happened automatically. Let me know if it's an issue with any new releases.

**Comment by xsivart** [comment]
Sorry was traveling this evening and visiting family.  Looks like that did it. All of the previous releases I was searching for are now showing up with sizes.

```
pynab=> select count(*) from releases where size is null and passworded='NO';
 count 
-------
     0
(1 row)

pynab=> select count(*) from releases where size is null and passworded='UNKNOWN';
 count 
-------
     0
(1 row)
```

Thanks :)

**Comment by Murodese** [comment]
Cool 😊
