### ISSUE TITLE
Optimise nzb creation by using PL/Python procedures.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#114]
I need to use this anyway, so I may as well learn to do it now!

NZB creation is pretty slow because we're constantly swapping a lot of data back/forth from postgre, and we use a lot of memory in doing so. If the server supports it, we should just be using pl/python to directly create and re-store the nzbs inside postgres so it doesn't even have to leave the server.

**Comment by Murodese** [comment]
Scratch that, it's about 60% slower unless I move all of release processing to PL/Python, which is a bit too complex for the payoff.

**Comment by brookesy2** [comment]
I thoroughly enjoyed this monologue :)

**Comment by Murodese** [comment]
I'll chuck the code up in its branch anyway just for interest's sake, but it's pretty slow :) Interesting if you want to know how to write python in postgres, though.

**Comment by Murodese** [comment]
Found #115 while I was writing it, too :)

**Comment by brookesy2** [comment]
Perfecto! I will have a read and hopefully learn something!
