### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jouty** [Murodese/pynab#116]
Does pynab decode obfuscated headers  like "abcodpoekdpo" to a good release header ?

**Comment by brookesy2** [comment]
As yet, no, I don't believe so. But I am trying to add some stuff to assist with this.

**Comment by jouty** [comment]
how to decode this ? regexp?

**Comment by brookesy2** [comment]
Could be lots of stuff. Sometimes its a hash of a release name, which you could work back from a pre to get. Other times you can find the release name from the nfo.

This post on reddit explains a lot of the situations :)

http://www.reddit.com/r/usenet/comments/1y73ar/obfuscated_post_file_names_how_to_discover_content/cfi33t2

**Comment by jouty** [comment]
"you can find the release name from the nfo." yes right but pynab and newznab just catch the header they don't grab all

**Comment by brookesy2** [comment]
pynab actually stores the nfo in postgres. I would have to leave Murodese to give more details. I am not super familiar with the code base, I am just trying to add to it!

**Comment by jouty** [comment]
thx a lot for your help brook

**Comment by brookesy2** [comment]
Any time!! :)

**Comment by Murodese** [comment]
It does, assuming it can find a name in one of three places:

1. the nfo (which we do grab as part of post-processing)
2. the filelist inside the rar header (likewise)
3. the sfv (likewise)

(also, if there's an imdbid in the nfo)

Effectively, it decodes most obfuscated names except for those without nfos that are within passworded rars. That's where pre-db's come in, which is what @brookesy2's working on.

**Comment by jouty** [comment]
Thank you very much for the help :)
https://github.com/Murodese/pynab/blob/development-postgres/pynab/releases.py this is the header decode function ?

**Comment by Murodese** [comment]
discover_name(), yes. It calls into the rar, nfo, sfv libs though.

**Comment by jouty** [comment]
i was thinking pynab just download the header so how can he catch the name in rar or nfo if download just headers
I mean i have miss something

**Comment by Murodese** [comment]
During post-processing, we download the first piece of the .rar file for each release (about 50kb) that contains file lists and such.

**Comment by Murodese** [comment]
I'm going to close this, but feel free to ask any other questions you have - they get emailed to me anyway.
