### ISSUE TITLE
Introduce a more streamlined way of running pynab.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#118]
It's a slight pain in the ass currently, and we want to build in use of Teamocil/Screen/Whatever and possibly Supervisor or Circus as well.

**Comment by Murodese** [comment]
I spent way too much time on this today ._.

**Comment by brookesy2** [comment]
That's a lot o'commits! lol Time to take a look :)

**Comment by Murodese** [comment]
Merged with development-postgres.
