### ISSUE TITLE
Pre Import Script

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#120]
I am thinking of adding a script that will format/insert the pre csv's that nzedb has on their dropbox:

https://www.dropbox.com/sh/fb2pffwwriruyco/AACy9Egno_v2kcziVHuvWbbxa

Easy way for people to populate their pre db's quickly.

Will probably base it off csvkit as the files are tab delimited and without a header row.

Worthwhile?

**Comment by Murodese** [comment]
Sure, toss it into scripts/.

**Comment by brookesy2** [comment]
Closing this. Will write it up.
