### ISSUE TITLE
Security: the default nginx configuration is not great

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#123]
Depending on the setup, the nginx configuration provided could lead to some security problems. To be safe, anybody running nginx with the provided uwsgi config should update their config as per the README.

Essentially:
1) Move /var/www/pynab to /opt/pynab
2) Change appropriate config files (/etc/nginx/sites-enabled/pynab.conf, /etc/uwsgi/apps-enabled/pynab.ini) for both the new path and the changes made in the README.
3) Restart both uwsgi/nginx.
4) Optionally, fix the permission errors that crop up.

**Comment by brookesy2** [comment]
I'm currently using this setup but have a question. Why this over any self
contained python web servers. Not questioning the decision, just want to
know more about why :)

**Comment by Murodese** [comment]
Something like cherry or paste, you mean? If it's running on a server that's already serving other stuff via nginx, you can't have two separate servers on port 80. You'd either have to run your other stuff on nginx on 80 and the API/webui on some other port, or use nginx for both.

I haven't tested performance, I suspect for most people paste/cherry would be fine.

**Comment by brookesy2** [comment]
Yeah, cherry etc. Had a feeling that might be why. I usually run on a
different port anyway or reverse proxy, which I guess is similar config
overhead to something like uwsgi.

Thanks for the quick response!
