### ISSUE TITLE
Migration to latest config update

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#124]
May want to update the readme to say people will need to upgrade their config file to include the monitor settings otherwise you will get:

Traceback (most recent call last):
  File "pynab.py", line 104, in <module>
    monitor = config.monitor.get('type', None)
AttributeError: 'module' object has no attribute 'monitor'

**Comment by brookesy2** [comment]
Hrmm, even with it and the pid_file added I still get:

error: a pid_file or logging_file config option is not set in config.py

Will continue to dig around and see.

**Comment by Murodese** [comment]
There are multiple pid_file options - one in api, scan, postprocess.

I've thought of better ways to do configs (namely generating it from a template or doing some kind of diff on-update) but haven't really had time. There's a note in the FAQ describing when to update the config, but I'll add this one explicitly.

**Comment by brookesy2** [comment]
Thanks!

I found the confusion. In the scanner config settings it says leave blank if using nginx, when it probably shouldn't say that in the scan settings.

All seems to be going now :)

**Comment by Murodese** [comment]
Huh, looks like I removed the daemonized usage anyway (since zdaemon's handling it), so none of the pid_files need to be set. I'll amend that (and the config).

**Comment by Murodese** [comment]
Oops, and I actually went to catch that error but missed it. Caught the wrong module :v

**Comment by brookesy2** [comment]
Legendary!! Let me know and I will remove all the pid config stuff and see if it works :)
