### ISSUE TITLE
How can I make sure my nn+ regex is being used?

### ISSUE THREAD

**Issue by AlanKK** [Murodese/pynab#129]
I am getting a lot of regex errors such as:

2015-01-16 22:34:38,894 - ERROR - imdb: [338039] - [The.Walking.Dead.S05E01.HDTV.XviD-AFG] - movie data not found: no suitable regex for movie name

**Comment by Murodese** [comment]
That's not actually an nn+ regex problem, it's trying to use imdb to parse a tv name - meaning that the release is miscategorised. Which group is that release coming from?

(query: `select group_id from releases where id = 338039`)

**Comment by AlanKK** [comment]
You are right that it wasn't a regex issue but I didn't have any regex's in the db.  My nn+ key wasn't configured.  Running "python3 pynab.py regex" did nothing.  There is a problem with arg parsing that prevents update_regex() from working.

**Comment by Murodese** [comment]
If it did manage to miscategorise that release, tell me which group it came from - the standard category for a release of that name is the correct one, so one of the group-based regex orderings is probably not working properly.
