### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by pmioulet** [Murodese/pynab#138]
Hi there,

Thanks for creating this project. I'm going to try it out and I'd be keen to run it on a Synology Nas using the MariaDB database.

You however suggest to use a postgres DB in the install doc. Switching from one DB implementation to another in java is (usually) pretty simple, but not too sure how much work it would involve on your python project. Would you mind to comment on this please so I know if there's any chance to do this ?

Thanks again, cheers.

**Comment by Murodese** [comment]
It's pretty simple in this too (since we're using SQLAlchemy), but there's a rather large caveat:

I'm using a postgres-specific optimisation during the segment saving process that speeds up that function from ~50 seconds for 50,000 segments to 0.8 seconds. Obviously, the 50 second version would be completely unworkable (which is why I chose to use the optimisation). I can look and see if Maria has something similar, but I think last time I looked they didn't. I'll check it out tonight.

**Comment by Murodese** [comment]
Oh, they do have it: https://mariadb.com/kb/en/mariadb/documentation/sql-structure-and-commands/sql-commands/data-manipulation/load-data-into-tables-or-index/load-data-infile/

I'll implement this tonight in another branch. I ~think~ that's the only thing preventing support.

**Comment by AlanKK** [comment]
That's awesome!  I think many people moving from newznab would prefer MariaDB or Mysql.  I am more familiar with them than postresql.  Are there any downsides to using Maria/Mysql that you know of?

**Comment by Murodese** [comment]
I used to use mysql for a lot of stuff, but I've only ever really used two dbms with the hilariously large dataloads that we're playing with here: mongo and postgres. I assume mysql/maria/percona should cope fine, once this other optimisation is in.

**Comment by pmioulet** [comment]
Thanks heaps for thi. Only reason I want to use maria instead of postgres is that postgres is used by the synology Nas for internal reasons so I'd rather not crash that DB by putting an inside load on it. I'm more comfortable risking the mariadb instance!

**Comment by Murodese** [comment]
Maria 5.5 is horrendously painful to get running on Ubuntu 14.04, so I'm going to use mysql for testing and you can test it against maria yourself :v

**Comment by Murodese** [comment]
If I've learned one thing from this exercise, it's that mysql is annoying as shit >: (

**Comment by Murodese** [comment]
`sqlalchemy.exc.ProgrammingError: (ProgrammingError) (1146, "Table 'pynab.releases' doesn't exist") "\nCREATE TABLE releases...`

That's mysql refusing to create a table because the table doesn't exist yet.

wat

**Comment by Murodese** [comment]
It just took me a disgusting amount of time to discover that a FK type didn't match a PK type, because mysql reported no errors at all except a generic dropped connection error.

I hate my life.

At least it works now!

**Comment by Murodese** [comment]
Ok, this is in the `maria` branch. Do a `git clone` and then `git checkout maria`. There's some very sparse notes in the readme - notably, you need to add `local_inline=1` to your my.cnf. The rest of the install instructions should be mostly fine. If you run into problems, don't hesitate to ask.

Note that it is considerably slower than postgres, by about 40%. MySQL has some quirks that require slightly slower ways of doing things, unfortunately.

**Comment by pmioulet** [comment]
thanks heaps for this, i'll be trying it out this w-e

**Comment by Murodese** [comment]
I've tested this for postgre use extensively, so I'm going to remerge it into development (since there are some general fixes in there too). So, just `git checkout development-postgres` instead.

**Comment by brookesy2** [comment]
After this merge I get this error when starting anything. Any thoughts?

python3 pynab.py scan
Traceback (most recent call last):
  File "pynab.py", line 20, in <module>
    import pynab.util
  File "/media/storage/git/pynab/pynab/__init__.py", line 99, in <module>
    check_config()
  File "/media/storage/git/pynab/pynab/__init__.py", line 28, in check_config
    inner_level = set(getattr(config_sample, item).keys()) - set(getattr(config, item).keys())
AttributeError: 'module' object has no attribute 'postgre'

**Comment by Murodese** [comment]
Delete your config.py and recreate it from config_sample.py.

**Comment by brookesy2** [comment]
I merged in all the missing bits. Let me take a look again and see.

**Comment by brookesy2** [comment]
Found it, happy days :)

**Comment by Murodese** [comment]
I'll fix the config checker too :)

**Comment by brookesy2** [comment]
The checker is hella handy. It only broke down due to change of postgres to db.

**Comment by Murodese** [comment]
Yeah, that's fixed now.

**Comment by Murodese** [comment]
Added in 1.5.0.
