### ISSUE TITLE
scan.py not starting properly?

### ISSUE THREAD

**Issue by xsivart** [Murodese/pynab#139]
Just updated to the latest development-postgres commit (37d55b7) and I noticed when simply running `python pynab.py start` it is spawning off the processes I want (scan/postprocess) but scan is not doing anything because it is not providing a group. The zdaemon config shows it running "python3 scan.py update" and running that manually on the command line produces:

```
pynab # python3 scan.py update
Usage:
    pynab.py update <group>
    pynab.py backfill <group> [--date=<date>]
```

I checked my init script because I wrote my own for OpenRC-based systems but all I'm running in the init script is `python3.3 /var/www/localhost/htdocs/pynab/pynab.py start`.

The log file is only showing:

```
2015-01-21 18:32:30,410 - INFO - log: started pynab logger
2015-01-21 18:32:41,097 - INFO - log: started pynab logger
2015-01-21 18:32:51,794 - INFO - log: started pynab logger
2015-01-21 18:33:02,488 - INFO - log: started pynab logger
2015-01-21 18:33:08,158 - INFO - log: started pynab logger
```

strace output of the zdaemon process shows it is only showing the same usage reminder that appears when running `python3 scan.py update` manually.

**Comment by Murodese** [comment]
My bad!

**Comment by xsivart** [comment]
That did it! Thanks :)
