### ISSUE TITLE
Implement a backup method.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#143]
I just accidentally dropped my entire production db and it would've been nice to have a backup.

o_______________o

**Comment by brookesy2** [comment]
pg_dump to the resuce! :)

**Comment by Herkemer** [comment]
I was thinking about this today, some sort of export that generates .json files similar to what gets loaded as part of the install might work.  You could tar/gzip that directory structure as part of your backup and then restore later if necessary.  Once gotcha might be if the schema changes, the .json files might not be able to load, but that could be mitigated.

**Comment by Murodese** [comment]
Actually not really a problem, because we can just save the alembic revision ID and revert back to that, do the import, then upgrade back to head. I'll have a think about it.

**Comment by Herkemer** [comment]
If all you had was a dump of the NZB file would that be enough? or is there other metadata stored in the database that you really want to hold onto?

If it's just the NZB file, then perhaps a simple export.py combined with an import.py would work.

I guess that doesn't cover users/groups, but dumping those in some sort of importable json format should be pretty easy in the long run.

**Comment by Murodese** [comment]
Yeah, probably. You'd have to re-do post-processing, but that's not a huge issue. A dump of the core tables (basically the same ones copied over in newznab-pynab conversion) and an nzb dump would work fine, I think.
