### ISSUE TITLE
Disappearing releases

### ISSUE THREAD

**Issue by AlanKK** [Murodese/pynab#149]
I am a little worried about my releases.  After importing nzb's a couple of weeks ago, I had 270,000 releases.  That climbed quickly to 400K.  Around that time, backfilling had finished and I extended the backfill_days by +10.  Since then, I have been losing releases pretty quickly and now have 60,000 fewer than when I started with pynab.  What is going on?

From stats.csv:
![image](https://cloud.githubusercontent.com/assets/6281705/5976208/44dac6be-a859-11e4-936b-df6c14ef31d0.png)

**Comment by Murodese** [comment]
I suspect most of them are misc releases that get deleted as postprocessing fails to access their rars, meaning they're passworded or junk releases anyway. If you want to keep them around for some reason, you can disable that behavior in your config.

**Comment by Murodese** [comment]
I should add - because primary use is for APIs, pynabs default settings keep the index very clean - releases are either determined good or are deleted. Again, you can change this behavior in the config.

**Comment by AlanKK** [comment]
ok, thanks

**Comment by Murodese** [comment]
Sorry, was replying on my tablet last night. For some more info:

There's only a few cases in which releases get deleted during post-processing (with default settings):

1) pynab is unable to access any rars, meaning that the release either didn't contain any (spam) or they've been DMCA'd.
2) the release has a bad name (uncategorisable) and we've been unable to fix that name using rar checking, nfo, sfv, pres.
3) the release gets picked up by a binary blacklist applied later (if a release has later been renamed to a foreign release and you have a foreign blacklist on, for instance)
4) the release is either passworded or probably passworded (you can choose which or both of those categories to delete)

Number 2 is actually disabled at the moment to give me a chance to see if we can rename them in any other ways. The rest apply, though.
