### ISSUE TITLE
Base URL and SSL proxying not well supported

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#153]
Just migrated from newznab, what a refreshing experience this has been.

I proxy pynab through an Apache SSL instance with a non '/' base URL, eg. clients access the service via 'https://somehost/pynab'.

I discovered pynab doesn't support this so well out of the box (using pynab 1.4.0).
So far, I've gotten it working by:
1. Adding a 'X-Forward-Protocol' request header to the front end proxy configuration
2. Modifying api.py:get_link() to check the headers and set wsgi.url_scheme to https as needed
3. Modifying api.py:get_link() to append request.environ['SCRIPT_NAME'] to the returned URL

I don't know if this the best/right way, I just hacked something in to work for my install.

**Comment by Murodese** [comment]
Just to check I have this right, you're trying to use the url 'http://somehost/pynab' rather than 'http://somehost/api' (the default)?

Might be easier if you paste me an example API request URL so I can have a look.

**Comment by gkoh** [comment]
Ah, not quite.

I configure the client (eg sickbeard) to use something like this:
https://somehost/pynab
which then gets newznabified into:
https://somehost/pynab/api?apikey=xxxx

The resulting NZB URLs look like this though:
http://somehost/api?apikey=xxx&blah&blah

ie the returned results drop both the HTTPS and base URL path.

**Comment by Murodese** [comment]
Ah, right. I'll take a look at this when I get home - looks like you've done the right thing anyway, though. get_link() is there for pretty much that exact reason, to handle edge cases.

**Comment by gkoh** [comment]
Great, thanks!

Rather than have you read my mind, here's my diff/hack:
"""
diff --git a/api.py b/api.py
index 51e1d2b..fb95d6d 100644
--- a/api.py
+++ b/api.py
@@ -93,6 +93,9 @@ def switch_output(data):
 
 def get_link(route=''):
     """Gets a link (including domain/subdirs) to a route."""
+    if request.environ.get('HTTPS') == '1':
+        request.environ.set['wsgi.url_scheme'] = 'https'
+
     url = request.environ['wsgi.url_scheme'] + '://'
 
     if request.environ.get('HTTP_HOST'):
@@ -107,6 +110,7 @@ def get_link(route=''):
             if request.environ['SERVER_PORT'] != '80':
                 url += ':' + request.environ['SERVER_PORT']
 
+    url += request.environ['SCRIPT_NAME']
     if route:
         url += route
 
"""

**Comment by Murodese** [comment]
Butchered by github! :)

**Comment by gkoh** [comment]
Bah, it seems gist is supposed to be the right way to do this:
https://gist.github.com/gkoh/d84c88e15158dc17b769

**Comment by gkoh** [comment]
And updated the previous comment to code-block it, thanks for that.

**Comment by Murodese** [comment]
Try that - you'll need to switch to the development-postgres git branch if you're not already on it.

**Comment by gkoh** [comment]
Looks good! Thanks for the exceedingly rapid response.

It may be worth noting in the documentation somewhere that the front end web proxy will need to add the HTTPS envvar, eg my apache SSL proxy has this:
```
SetEnvIf X-Forwarded-Protocol https HTTPS=1
```

**Comment by Murodese** [comment]
Added a note, but I have no experience with this, so if you want to clarify it feel free :)

**Comment by gkoh** [comment]
That works for me, I'm all good with closing this.
Thanks once again.
