### ISSUE TITLE
Zdaemon sucks and needs to be replaced.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#154]
Supervisor is a good replacement.

**Comment by Murodese** [comment]
Fixed in 1.5.0.

**Comment by brookesy2** [comment]
Yo, is the init file supposed to say this:

 [program:scan]

or:
[pynab:scan]

As python3 pynab.py start produces:

pynab:scan: ERROR (no such process)

**Comment by brookesy2** [comment]
Oh, I may see why, perms issue on my log dir I think.

**Comment by brookesy2** [comment]
That was 100% the issue, ignore me :)
