### ISSUE TITLE
pre req is not processing a.b.etc

### ISSUE THREAD

**Issue by ukharley** [Murodese/pynab#157]
a.b.etc is basically the same as a.b.teevee as far as req's go so I changed this in my requests.py, line 34 to 37

            pregroup = requests.get(pre.requestid).group.name
            if pregroup == 'alt.binaries.etc':
                pregroup = 'alt.binaries.teevee'
            if pre.requestgroup == pregroup:

**Comment by ukharley** [comment]
Checked the db and search_name, name are still unchanged from REQ: xxxx to proper name. Will check further.

**Comment by brookesy2** [comment]
How odd. It just looks in the pre table for a REQ/Group match, if there are none it will do nothing. I guess the solution you have provided would work though (if they are indeed the same)

**Comment by ukharley** [comment]
As far as REQ ID's go, they are the same.

**Comment by brookesy2** [comment]
@ukharley Awesome, TIL :) Slap in a PR for it!

**Comment by Murodese** [comment]
> IGNORE THIS. DEBUGGER WAS PAUSED LOL.

lol

**Comment by brookesy2** [comment]
hahaha. Thats awesome :)

**Comment by ukharley** [comment]
Can't PR it, it's just a quick fix. It needs to be done properly so logs etc reflect it's from a.b.etc. As I'm at work and shouldn't be playing on my home PC, I'll leave it to you or MD. I'll only be able to give it good look over the weekend if you wnat me to do it.

**Comment by Murodese** [comment]
That should work, but I don't have any REQs left to test it on (or at least none that I have IDs for).

**Comment by Murodese** [comment]
Well, this part worked at least:

> 2015-02-12 19:21:16 INFO release: [REQ: 147311] - rename: Dr.DEATH.2001.DVDRiP.X264.mkv (8010 -> 8010 -> 2030)

**Comment by brookesy2** [comment]
I can fix it over the weekend :)

**Comment by Murodese** [comment]
Nah, seems to be working fine. If you could test it that'd be good.

**Comment by Murodese** [comment]
I'm backfilling a.b.movies at the moment, I'll do etc after that.

**Comment by brookesy2** [comment]
Will add the etc/movies duality :)

**Comment by Murodese** [comment]
Already did :)

**Comment by brookesy2** [comment]
Iv said it once, but I will say it again, gentleman and a scholar :)

**Comment by ukharley** [comment]
Had to update requests.py to this as it wasn't working (line 45ish):
            if pre.requestgroup == pre_group:
                updated_release = requests.get(pre.requestid)
                updated_release.pre_id = pre.id
                updated_release.search_name = pre.name
                db.merge(updated_release)
                log.info("requests: found pre request id {} ({}) for {}".format(pre.requestid, pre_group,

**Comment by Murodese** [comment]
No - it's not meant to update the name at that stage. The name gets updated during rename_bad_releases in postprocessing, where the req name becomes a candidate for naming. You won't see it immediately change the name, but it'll change it shortly after.

**Comment by ukharley** [comment]
OkyDoky. Just wasn't renaming an a.b.movee release.

**Comment by Murodese** [comment]
As long as it properly matches the pre to the release, it should get renamed next postprocess iteration.

**Comment by ukharley** [comment]
Thanks. If it happens again, I'll start by looking in r_b_r.
