### ISSUE TITLE
Postprocessing is really, really slow

### ISSUE THREAD

**Issue by ajoergensen** [Murodese/pynab#158]
I updated to 1.5.0 last night;

after restarting:

`2015-02-11 23:12:48 INFO postprocess: starting with a quick post-process to clear out the cruft that's available locally...`

Now, 15 hours later it's still at this step in post processing; I recently imported 1.5 mio releases so there's a lot to do, but it's only processing one release every 30-45 seconds.

`/usr/bin/python3 /opt/pynab/postprocess.py` is using 100% CPU but I cannot figure out why.

**Comment by Murodese** [comment]
What kind of output do you get if you chuck logging on `logging.DEBUG`?

**Comment by ajoergensen** [comment]
Mostly

`2015-02-12 14:41:05 DEBUG tvrage: [Secret Series S02E03 ] - tvrage failed: no show found (local)`

(These are the ones that are 30-45 seconds apart; occasionally there will be an INFO message like `INFO tvrage: add local`)

**Comment by Murodese** [comment]
Huh, odd. Lemme take a look.

**Comment by Murodese** [comment]
What's the memory usage of the script while it's doing that? Pretty high?

**Comment by Murodese** [comment]
Try that and see how it goes (development-postgres branch).

**Comment by ajoergensen** [comment]
A little more than 3GB; I thought it might have been because I forgot to change max_process_anyway to false (after creating a new config.py).

I'd rather not switch to development-postgres :) - Any other way to test it?

**Comment by Murodese** [comment]
About... 3.2gb? ;) I'm guessing it's hitting the memory limit for 32-bit processes and it's having to swap to the HDD, which is hilariously slow. That fix should take care of it.

You should be able to check out that one file by doing...

   > git checkout development-postgres -- pynab/tvrage.py
   > git checkout development-postgres -- pynab/imdb.py

That should check out the new versions of just those two files (which are the ones that are changed). I have no idea what it'll do the next time you try to update, though.

**Comment by aljdk** [comment]
It's flying again :)

(I ended up cloning development-postgres elsewhere and copying the two files; manual cleanup when the fix makes it to master)

**Comment by ajoergensen** [comment]
It's flying again :)

(I ended up cloning development-postgres elsewhere and copying the two files; manual cleanup when the fix makes it to master)

**Comment by Murodese** [comment]
There's been a few minor bugs fixed that could potentially cause issues, so I suspect the next point release won't be too far away - a maybe this weekend.
