### ISSUE TITLE
Cannot have empty username and password for news server

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#163]
Just upgraded from 1.4.0 to 1.5.1, now getting an authentication error:
"ERROR server: no username or password supplied"

It appears that a check was added to pynab/server.py to ensure the username and password for the NNTP server must be non-empty.
Unfortunately, I'm inside a network where there are no credentials needed to use the NNTP server.

I have commented out the check for now to keep it going.

**Comment by Murodese** [comment]
No problem, I've removed it again. Thanks!

**Comment by gkoh** [comment]
Sorry didn't get back to this for a bit.
You could check for empty vs non-existent, ie None vs empty string?
Otherwise, the fix works well for me.
