### ISSUE TITLE
Trouble with INSERT INTO files during postprocessing

### ISSUE THREAD

**Issue by Herkemer** [Murodese/pynab#174]
Howdy,

I'm seeing this error during postprocessing:

sqlalchemy.exc.DataError: (DataError) value too long for type character varying(512)
 'INSERT INTO files (name, size, release_id) VALUES (%(name)s, %(size)s, %(release_id)s) RETURNING files.id' {'size': 439362345, 'release_id': 28915, 'name': '...BASICALLY WHAT LOOKS LIKE GARBAGE...BUT LONG...'}

These filenames feed into potential_names, and I'm not totally sure what value these names have.

I was thinking we could either a) simply truncate and hope for the best or b) just not insert files that have too long of a name.

We could also try increasing the size to avoid potential issues, but I still think some sort of limiting will be necessary in the long run.

Thoughts?

**Comment by Murodese** [comment]
Truncate. I really doubt that any proper names are going to be >512char.
