### ISSUE TITLE
Invalid Literal error when processing requests

### ISSUE THREAD

**Issue by rembo10** [Murodese/pynab#178]
I'm trying to index a.b.inner-sactum and getting an invalid literal error when it tries to process requests. The requests are like: 'REQ: 5936dc6fb392964e4e77108cdefe4430'

And the error I get is:
2015-03-07 05:35:21 CRITICAL Traceback (most recent call last):
  File "/opt/pynab/postprocess.py", line 66, in process_requests
    return pynab.requests.process(500)
  File "/opt/pynab/pynab/requests.py", line 22, in process
    requests[int(release.name.split(': ')[1])] = release
ValueError: invalid literal for int() with base 10: 'b8878592fda380841dee2642c140ae1c'

**Comment by Murodese** [comment]
Should be guarded in 8f1d6e710d7bbfd60dc5c080a006594f972b43a0, but we have no predb for inner-sanctum, so it won't be able to rename those releases anyway.
