### ISSUE TITLE
Re-postprocessing Releases

### ISSUE THREAD

**Issue by rembo10** [Murodese/pynab#180]
Hey - so - in my haste I didn't realize there was a delete_spam_groups option (I'm only indexing music and had such a one track mind that I didn't consider that certain groups would want .exe files)...... anyways, now I have a bunch of releases that contain .exe files for music categories, and I was wondering if there was a way I could go through those releases and delete anything with an exe.

Thanks for the help!

**Comment by rembo10** [comment]
Eh, I guess I can close this. I just wiped the database and am reindexing. Should have been more careful....

**Comment by Murodese** [comment]
Shouldn't have wiped. Spam detection happens at postprocessing after inner file checking is done, so pretty much just leave it and it'll handle it.

**Comment by Murodese** [comment]
The config file is a pretty good indicator of what happens where. If it's in the postprocess section, it happens during postproc (except for min_completion/min_archives, those happen during scans). ~Most~ stuff relies on rar checking to occur, so if you have a big backlog of releases it'll take a little while to get through all of them.

As an example, I reindexed everything a few weeks ago and CouchPotato picked up a couple of spam releases because rar post-processing happens in newest-oldest order, so it hadn't gotten to those ones and determined they were spam/deleted them yet. Just gotta give it time.

**Comment by rembo10** [comment]
So if I edit the config file, would it pick up on the changes and go through the releases again? Sorry - I’m gonna start digging through the code today to figure out how it all works, was just curious

**Comment by rembo10** [comment]
Also, shouldn't post-processing occur before it's added to the releases?

**Comment by Murodese** [comment]
No, post-processing happens after it's created the release. Scanning's basically broken into two parts:

- Scanning: grab post indexes, aggregate into binaries, turn completed binaries into releases
- Post-processing: grab release rars and get inner file info, match to tvrage/imdb, rename from files/sfv/nfo, delete spam based on inner file checking, etc

The idea is that post-processing (if you have a big backlog) can take quite a while, so you push the releases out as quickly as possible, but without associated metadata. It runs basic checks before doing this - is the release complete? Does it satisfy min_archive rules? etc. At this point, you can manually download the releases and any software that doesn't require metadata matches can search for it and grab it (including anything that uses RSS). After that, it goes through post-processing - once that's done, software that searches based on tvr/imdb ID or the like can access it.

So yeah, if whatever you're doing happens at post-processing you can just edit the config and restart the daemons. If it's something that's checked periodically (deleting passworded releases, spam checking, renaming, etc) it'll pick it up next iteration. If it's something done at scan-level, though, it'd have to be rescanned.

Most of the time if it's something a little weird you can just post an issue and I can write a quick query to fix it - if it's a useful feature, it'll usually be added to a script, the pynab console or as part of post-processing anyway.

**Comment by rembo10** [comment]
Is it possible to add an option to only expose post-processed releases to the api?

**Comment by Murodese** [comment]
I can certainly add that option.

**Comment by rembo10** [comment]
That would be amazing. I love this project. I’ll try to contribute soon

**Comment by Murodese** [comment]
I should mention that I haven't tested this. COULD BREAK EVERYTHING

Really wish I had more time in a day

**Comment by Murodese** [comment]
I should add that it's off by default.

**Comment by Murodese** [comment]
Also, glad you like it! It's been a lot of fun to work on, and I've learned a lot about dealing with massive amounts of data.

**Comment by rembo10** [comment]
I’m not sure if this will work because some things might be post-processed but might not have any rar archives (speaking specifically for music releases here). Sometimes it’ll just be the mp3 files, so passworded will stay at UNKNOWN (I think?). Otherwise it would make sense. What about adding in a processed column or something as ’t’ or ‘f’ and then filter it out that way? but i guess things are run separately in chunks, so it might not work (e.g. it’s gone through the rar process but not sfv…..). I’m looking through the code now so might be able to come up with something.

Quick unrelated question - there are some posts that aren’t being picked up by the nn+ regex. e.g.
Imagine Dragons - Smoke + Mirrors (2015) "01 - Shots.mp3" yEnc 
from a.b.sounds.mp3.complete_cd

I came up with a regex that will catch it, but i’m wondering if there’s a way to pick it up retroactively? if i just add it to the regex table will it try to match, or is it only done at scan-level? and if i wanted to rescan, how would i do that?

so sorry for all the questions. really, i love this project - newznab and nzedb seem so bloated and only run on mysql so this is like a godsend

**Comment by Murodese** [comment]
Don't worry about asking questions, they give me good ideas on how to improve things!

Regex is only applied at scan-time, so you'd need to rescan. You can do that by resetting the group (`./pynab.py group reset <group>` from memory) and just backfilling it again - pynab will automatically discard any duplicates, so it should only pick up new stuff.

Note that the default setting in pynab is to discard any releases that don't contain at least one archive, so if the music isn't in an archive you'll need to change the min_archives section of your config to reflect that (ie. set alt.binaries.mp3.complete_cd to 0). I think most stuff is in archives, though - though sabnzbd or whatever you use will generally automatically extract them for you.

There's no real definition in the project for when postprocessing is "complete" for a release, unfortunately. For TV releases, "finished" means we've matched it to tvrage and episode info, have checked for passwords/exes/spam, etc. For Movies, it's that we've matched it to imdb, have an nfo, etc. For most stuff, determining whether a release is spam and attempting to grab the first piece is enough - we exclude spam releases, exclude passworded releases and determine whether the file can be downloaded (if the first piece is missing, there's a pretty good chance that the rest is dead). This criteria satisfied most of my good releases - TV episodes, Movies, etc, but I don't index music. If you can take a look at some of your releases and see what they come out as before/after postproc, it'd be appreciated.

**Comment by rembo10** [comment]
I appreciate that. I’m just trying to figure out how it all works

I mean, basically it’s working great. The spam releases are only exposed for a couple minutes, and the only thing left is updating the regex to pick up some stuff that it’s missing (which is more to do with nn+ than your project).

I changed the default setting to pick up releases without archives, so that’s working out. 

Here’s an example of a release before and after post-processing:
http://pastebin.com/BDF95gp0 <http://pastebin.com/BDF95gp0>

I guess this one had a rar in it, so it set passworded to NO, but if you look at the last entry, it’s for bloc party, which was just a bunch of mp3 files, and it keeps passworded at UNKNOWN (another thing that’s weird - for the release by dready (not the bloc party), the size goes from 105842272 -> 471877 after post-processing. Actual size is ~100mb)

Anyways, cheers for the help, it’s much appreciated.

**Comment by Murodese** [comment]
Yeah, the inner file checking needs improvement. What it does at the moment is find inner rars and pull the headers out, including file size. Obviously what it's doing here is going into the rar (whatever's inside it), getting the size and using that, when that's obviously erroneous, since the content is outside the rar. The vast majority of stuff I get is tv/movies and not music, so I haven't come across this much, but I'll take a look at it when I get time (or you can). I have noticed that it doesn't work well with e-books either, though, which all tend to not be archived.

**Comment by Murodese** [comment]
If you do want to take a look at it, this is the place to start: https://github.com/Murodese/pynab/blob/master/pynab/rars.py#L258

That line checks to see if there's a rar in the release and doesn't process it if there isn't, so you'd need to write the else handler - if there's no rar, it's not passworded (since it can't be) and you just need to check the sizes of the content files in the nzb details.

**Comment by rembo10** [comment]
I'll submit a pull request to handle releases without rars.

But just a quick question: what's the best way to go about testing
regexes?

It worked on http://pythex.org/ testing against the post subject, but
doesn't seem to be working in pynab.

Also, finding the right backlog date seems to be really slow. If I set the
date to 1 day it'll start at 3 days back and increment the post numbers by
2.... and on a.b.sounds.mp3.complete_cd that takes a while. But if I set it
to 3 days it starts at 10 days back at the far end and 1 day back on the
near end, again incrementing by 2 (at least I think that's how it works).
I'll go through server.py to figure it out but I though if you were around
I might be able to get some insider info

**Comment by brookesy2** [comment]
I use https://regex101.com/ similar to what you pasted :)

**Comment by rembo10** [comment]
Ah yeah, scratch that. My regex was working. It was just marking them as spam for some reason. I’m going to try to fix that & the rar file size issue today - and handling releases without rars

**Comment by rembo10** [comment]
If a regex doesn't contain <parts>, where does it store those parts, and how long before they're turned into releases? just want to make sure my regex is working..... the ones with <parts> work great

**Comment by Murodese** [comment]
Yeah, http://regex101.com is usually my choice.

Backlog datefinding is generally quick, but slows down the closer you are to 0 because we can't use some of the optimisations that can be used if it's >50 days or so. The spread of dates over the lifetime of a group isn't linear, so it's a bit of a guessing and checking game. The current iteration is the fastest it's been - we used to use the same method as newznab, but it was excrutiatingly slow. If you can think of a better way of doing it, let me know.

If parts don't match a regex, they're deleted immediately after binary processing (ie. when we go through parts and build binaries). If you want to test a regex, you'll have to re-scan some portion of the group that contains one of those releases.

**Comment by rembo10** [comment]
Where are they stored though if they don’t contain a part number, e.g.:

Of Montreal - Aureate Gloom (2015) "06 - Monolithic Egress.mp3” yEnc

with regex:
^(?P<name>.*\s-\s.*\s\([1-2][0,9]\d{2}\))\s\".*\..*\”\syenc

vs.

[138485]-[#altbin@EFNet]-[Full]-[Kanye_West-The_College_Dropout_(Remas tered)-(Read_NFO)-2005-VAG_INT]-[24/31] - "20-kanye_west-family_business.mp3”

with regex:
^\[\d*\]-\[.*\]-\[(?P<name>.*)\]-\[(?P<parts>\d{1,2}/\d{1,2})\]\s-\s".*\..*"\syenc$

**Comment by Murodese** [comment]
Is that the full subject name? Because even a release that has one part should have multiple segments - an mp3 isn't going to fit into 50kb.

**Comment by rembo10** [comment]
It'll look something like this:
![screen shot 2015-03-11 at 6 49 13 pm](https://cloud.githubusercontent.com/assets/801525/6610641/5e339d80-c81f-11e4-9f41-59074086b63d.png)

**Comment by rembo10** [comment]
It drops the segment though right? Like I don't need to include the segments in my regex, right?

**Comment by Murodese** [comment]
Correct, I was just wondering if you'd pasted that directly from usenet and it was missing segment numbering. 

There's nothing preventing parts without numbers from being stored in the DB, so presumably they're still in there. However, if there's no parts group in the regex, they're silently dropped it appears. You can fix that by just setting part number to 1 if there's no part listed. 

https://github.com/Murodese/pynab/blob/development-postgres/pynab/binaries.py#L155

**Comment by rembo10** [comment]
Awesome. Is there any way to apply regexes to all groups? With an asterisk maybe? Just because I’m only indexing music groups and they generally follow the same format

**Comment by Murodese** [comment]
The group names in the regex table should work effectively as a startswith, so alt.binaries.mp3 would match any group that starts with that (including mp3.complete_cd, mp3.albums, whatever).

**Comment by rembo10** [comment]
Awesome. Just having a bit of trouble trying to process stuff without part numbers. I can get them into releases (by setting the part number to ‘1/1’ - if I set it to 1, it gets skipped on https://github.com/Murodese/pynab/blob/development-postgres/pynab/binaries.py#L166 <https://github.com/Murodese/pynab/blob/development-postgres/pynab/binaries.py#L166>). But then when the release is formed it’s just the last file, i guess everything gets overwritten.

I think it needs some new logic to handle it but i’m not really sure how to figure it out

**Comment by Murodese** [comment]
Pass me the regex you wrote and the group you're working on and I'll take a look.

**Comment by rembo10** [comment]
regex: ^(?P<name>.*\s-\s.*\s\([1,2][0,9]\d{2}\))\s*\".*\..*\”\syenc

trying to pick up:

Of Montreal - Aureate Gloom (2015) "Of Montreal - Aureate Gloom (2015).par2” yEnc
Of Montreal - Aureate Gloom (2015) "10 - Like Ashoka's Inferno Of Memory.mp3” yEnc
Of Montreal - Aureate Gloom (2015) "09 - Chthonian Dirge For Uruk The Other.mp3”
Of Montreal - Aureate Gloom (2015) "08 - Estocadas.mp3" yEncOf Montreal - Aureate Gloom (2015) "07 - Apollyon Of Blue Room.mp3” yEnc
Of Montreal - Aureate Gloom (2015) "05 - Virgilian Lots.mp3” yEnc
Of Montreal - Aureate Gloom (2015) "06 - Monolithic Egress.mp3” yEnc
Of Montreal - Aureate Gloom (2015) "04 - Aluminum Crown.mp3" yEnc 
Of Montreal - Aureate Gloom (2015) "03 - Empyrean Abattoir.mp3" yEnc 
Of Montreal - Aureate Gloom (2015) "02 - Last Rites At The Jane Hotel.mp3” yEnc
Of Montreal - Aureate Gloom (2015) "01 - Bassem Sabry.mp3” yEnc

posted in a.b.sounds.mp3.complete_cd on 9/3/15

thanks man! you’re the best! i just ran a backlog for 2 years and it was blazing fast and picked up a ton of stuff. this is literally the best thing ever

**Comment by Murodese** [comment]
Cool, I'll take a look at it tonight :) Glad you like the project!

**Comment by brookesy2** [comment]
@rembo10 Give this a whirl. You may want to make the numbering more restrictive though.  

https://regex101.com/r/jW0lW3/1

**Comment by rembo10** [comment]
Oh - the problem wasn’t that I couldn’t pick it up with the regex, it’s that the parts get merged in binaries.py, when there’s no part number (i was putting in ‘1/1’  - so it would pass the check on line 166 (if '/' not in match['parts’])).

But I think it needs to be totally separate logic if there’s no part number. Like wait until the last post is 6 hours old, then create the release. It might be too much of a hassle though. It’s not the worst thing to just stick to releases with part numbers.

**Comment by Murodese** [comment]
I was just going through this now. There used to be some logic in there dealing with single-part releases, but they turned out to mostly just be spam so I culled it.

Is that github mangling those double quotes, or are they posted like that? (or both?)

**Comment by brookesy2** [comment]
@rembo10 Ahhh, ignore me then! lol

Yeah that is a tricky one, because there is no real way to know when it ends, like you said. Hard mode would be to go discover how many tracks are on it then match it.

**Comment by Murodese** [comment]
Ah, github had mangled the quotes. 

Those releases are tricky. Are there a lot of those, or are they just somebody mistakenly uploading the individual files instead of a release rar? 

It's relatively simple to keep them as individual releases (ie. per song) but it's going to be a nightmare to re-merge them into a single release.

**Comment by rembo10** [comment]
There probably aren’t enough to make writing the code worthwhile. The releases are usually posted within 10-15 minutes of each other, so we can say like, if there aren’t part numbers, and it’s been say 3 hours since the last post, form the release. 

I’m just not sure how to go about doing this but I can try.

**Comment by Murodese** [comment]
You'd have to write a seperate code path from L158 in binaries.py/process that deals with parts that do not have `match.get('parts')` and are over a certain age. I'd have a crack at it, but I don't really have time at the moment.

**Comment by rembo10** [comment]
I think i’d also have to modify releases.py to handle processing binaries without part numbers?

**Comment by Murodese** [comment]
Or just set total_parts to a count of whatever's available after 3 hours, I think.
