### ISSUE TITLE
COPY Error during parts save_all

### ISSUE THREAD

**Issue by Herkemer** [Murodese/pynab#182]
I'm getting a whole bunch of errors that look like this:

2015-03-10 05:17:40 ERROR COPY from stdin failed: error in .read() call: Unicode
EncodeError 'utf-8' codec can't encode character '\udced' in position 4351: surr
ogates not allowed
CONTEXT:  COPY segments, line 485
2015-03-10 05:17:40 ERROR group: problem saving parts to db, restarting scan

Not sure exactly what is causing it.

Going to try and debug it some more, but in case anyone else knows what is going on I wanted to put it out there.

**Comment by Murodese** [comment]
I haven't tested this and I don't really have time just now, but you can try it:

https://gist.github.com/Murodese/7bb6e9d685895e39e680

**Comment by Herkemer** [comment]
Haven't tried to debug it yet, but I got this pretty much right away:

AttributeError: 'int' object has no attribute 'encode'

**Comment by Murodese** [comment]
Yeah I had a bracket in the wrong place. I have this fixed in a commit but
I don't think I've pushed it yet.

**Comment by Herkemer** [comment]
Unfortunately I'm still seeing this.

**Comment by Murodese** [comment]
Can you paste the traceback? Subject should've been the only field that had wonky characters in it, but maybe poster as well.

**Comment by Herkemer** [comment]
No traceback, just the error from the copy code, here is all I've got:

2015-03-15 23:03:43 ERROR COPY from stdin failed: error in .read() call: UnicodeEncodeError 'utf-8' codec
 can't encode character '\udced' in position 4351: surrogates not allowed
CONTEXT:  COPY segments, line 485

2015-03-15 23:03:43 ERROR group: alt.binaries.tvseries: problem saving parts to db, restarting scan

Hmmm, looks like it was in the segments portion of the code and not the parts.

**Comment by Murodese** [comment]
That should be every field that accepts unicode, I think. Try that.

**Comment by Herkemer** [comment]
Ok, I was seeing it every run, with the changes I haven't seen it again.  I'll continue to watch as it runs for awhile longer.

**Comment by Murodese** [comment]
Cool. Interestingly, I've never seen that error in the year or so I've been running it.
