### ISSUE TITLE
NZB Import Broken?

### ISSUE THREAD

**Issue by rembo10** [Murodese/pynab#184]
Hey - I'm trying to import a few nzbs that I missed with my regexes, but I get the 'nzb: failed to import nzb' error for every nzb I try to import. Just looking through the code, it looks like it checks if 'name' is in release in nzb.py, line 197, but I can't see where the name would be added.....

using the dev branch

**Comment by Murodese** [comment]
L186 handles it. Error suggests that the nzb had no release name. Ungzip it and upload the XML in a gist or something.

**Comment by rembo10** [comment]
Sure, here’s something I was trying to import:
https://gist.github.com/rembo10/2dfb2d46b8a87e386e22 <https://gist.github.com/rembo10/2dfb2d46b8a87e386e22>

I got around the issue by setting the name to the nzb file name if it couldn’t find it in the xml
if 'name' not in release:
        release['name'] = os.path.splitext(os.path.basename(name))[0]

but for some reason it’s not setting the size correctly in the releases tables

**Comment by Murodese** [comment]
Size calculation's pretty simple, initially - it just uses xpath to grab every attribute value for bytes, then sums it. One thing might've blocked it with a corrupt nzb - that should be fixed, now.
