### ISSUE TITLE
MySQL Through Socket and Default Database Type

### ISSUE THREAD

**Issue by Enverex** [Murodese/pynab#187]
The MySQL connection details seem to be designed for TCP/IP, if MySQL has networking disabled you won't be able to proceed. There should be some way of using sockets instead (using "locahost" as the host doesn't use sockets).

Also unless InnoDB is set as your default engine, installation will fail with:
    Specified key was too long; max key length is 1000 bytes

The install script should specify InnoDB in the table creation stage if it specifically needs InnoDB. That said, InnoDB still fails with "Specified key was too long; max key length is 767 bytes" so I'm not sure what it wants here.

**Comment by Murodese** [comment]
I'll take a look at this later today. The error you got related to max length: was that during installation?

**Comment by Enverex** [comment]
Yeah, first stage of the config where it's trying to set up the tables. UTF-8 InnoDB tables can only be 1000 bytes (VarChar of 333) and MyISAM/Aria are limited to 7xx bytes.

I'm using Postgres for now but would prefer not to run two different database systems due to their RAM usage.

**Comment by Murodese** [comment]
Strange that I didn't have these errors when I was testing the MySQL version. Let me have a play.

**Comment by Murodese** [comment]
Ok, I've got a solution for this, needs a bit more testing. I'll finish it off tomorrow.

**Comment by Enverex** [comment]
Great. Now the question is - can I migrate from the PostgreSQL database or do I need to start over?

**Comment by Murodese** [comment]
You should be able to dump out the tables as csv and reimport them, but that's not something we natively support. I also wouldn't do that with the parts tables - finish processing first.

**Comment by Murodese** [comment]
I'll uh, let you know if this works. I have a rather large release table and the DB migration is taking.. a few hours.

**Comment by Murodese** [comment]
Nevermind, it was locking. Try that.

**Comment by Enverex** [comment]
You're a dedicated man :P I'll give it a try now and report back. Thanks.

**Comment by Murodese** [comment]
Yeah, ignore the fact that it's called development-postgres. All new patches/bugfixes go to the dev branch for a bit before they get merged to master.

**Comment by Enverex** [comment]
Install seems to fail in the same fashion still...

   sqlalchemy.exc.InternalError: (InternalError) (1709, 'Index column size too large. The maximum column size is 767 bytes.') '\nCREATE TABLE users (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tapi_key VARCHAR(32), \n\temail VARCHAR(256), \n\tgrabs INTEGER, \n\tPRIMARY KEY (id), \n\tUNIQUE (api_key), \n\tUNIQUE (email)\n)CHARSET=utf8 ENGINE=InnoDB\n\n' ()

**Comment by Murodese** [comment]
Yeah, different error. Previous one was dying on a unique index, this is just an index. One way to fix it is to revert the charset to something 1 byte wide, I guess - UTF8 support is somewhat irrelevant since release names are in ASCII. There's no other good way to do the indexes though - I could replace the unique with a hash since that was a lot faster anyway, but we actually need to index the string with this one.

**Comment by Enverex** [comment]
I thought that's what your change did, you added a new key which was a hash of the original value you were keying and indexed that instead?

Is this another value in another table that is tripping it up now? Looks like I somehow didn't mention which key in which table was at fault originally, whoops.

**Comment by Murodese** [comment]
Yeah, originally it was a unique key for releases (name, posted, group) that I hashed. This is actually a key index on name, so I can't use a hash (because that would defeat the purpose of using an index).

**Comment by Enverex** [comment]
Good point. Using a single byte charset would allow for up to 767 characters in InnoDB I believe. Would that be long enough?

**Comment by Murodese** [comment]
Yeah, 512 is the max length on most fields except xref (which isn't indexed). I'll make it something more appropriate.

**Comment by Murodese** [comment]
Try that. Also, interesting that you're missing the binaries table - indicates that your install failed. Is this with the config to postgre or mysql?

**Comment by Enverex** [comment]
Technically this shouldn't be a problem as long as people are on MySQL 5.6 / MariaDB 10:

https://mariadb.com/kb/en/mariadb/xtradbinnodb-server-system-variables/#innodb_large_prefix

That said, I can't seem to get it to work. May be worth looking into this first before changing how PyNab itself works as this would be less hassle for you.

**Comment by Enverex** [comment]
You can't install using MySQL, it fails because it can't create the table structures (sorry if I didn't make that clear before, I thought I mentioned it).

Installing using PostgreSQL instead instead works fine.

**Comment by Murodese** [comment]
Yeah, I meant the update sorry. That's only necessary if it's a running installation, otherwise just try install.py.

**Comment by Enverex** [comment]
New error:

    Problem inserting data into database: 'latin-1' codec can't encode character '\u0192' in position 10: ordinal not in range(256)

That said, if you enable innodb_large_prefix in MySQL and use "DYNAMIC" tables, you can use VARCHAR rows over 1000+ as UTF8 as it allows 3072 bytes which may be useful.

**Comment by Murodese** [comment]
Yeah, probably a better solution. I'll change it back to UTF8 - did you manage to get innodb_large_prefix working?

**Comment by Enverex** [comment]
Yeah. It claims to be boolean but only accepts 0 or 1 (rather than yes/no). Added a 1000 varchar UTF-8 row without issues.

**Comment by Enverex** [comment]
FYI, the changes needed to get MySQL to support this are:

    innodb_large_prefix             = 1
    innodb_file_format               = Barracuda
    innodb_file_per_table           = 1

And making sure that when you create the table, you use "ROW_FORMAT=DYNAMIC;", e.g.

    CREATE TABLE t3 (a INT, b CHAR (20), PRIMARY KEY (a)) ROW_FORMAT=DYNAMIC;

And all should be fine.

**Comment by Murodese** [comment]
Cool, I'll find the appropriate sqlalchemy option.

**Comment by Murodese** [comment]
Ok, that should do it.

**Comment by Enverex** [comment]
Seemed to work. Noticed lots of warnings though.

	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Duplicate entry '170701-2014-01-10 11:46:11-alt.binaries.teevee' for key 'requestid'
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Duplicate entry '31354-2012-09-10 14:00:52-alt.binaries.mp3' for key 'requestid'
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Duplicate entry '6762-2012-08-06 08:32:26-alt.binaries.hdtv.x264' for key 'requestid'
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Duplicate entry '9154-2012-07-05 03:36:59-alt.binaries.hdtv.x264' for key 'requestid'

Then followed by some of these lines...

	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Out of range value for column 'nuked' at row 2876
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Data truncated for column 'pretime' at row 2876
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Incorrect integer value: '' for column 'requestid' at row 2876
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Out of range value for column 'nuked' at row 2877
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Data truncated for column 'pretime' at row 2877
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Incorrect integer value: '' for column 'requestid' at row 2877
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Duplicate entry '0-0000-00-00 00:00:00-' for key 'requestid'
	  result = self._query(query)
	/usr/lib/python3.4/site-packages/pymysql/cursors.py:134: Warning: Incorrect integer value: '' for column 'nuked' at row 2878

Not sure if either of those blocks are actually anything to worry about though.

**Comment by Enverex** [comment]
Also I'm seeing this a lot now. Not sure if it's related to any of this but I've not seen it before so I thought I'd mention it. It's popping up a lot during post-processing:

    2015-03-28 17:20:42 CRITICAL nzbs: problem parsing XML with lxml: Compressed file ended before the end-of-stream marker was reached

**Comment by Murodese** [comment]
This is with the fresh mysql install?

**Comment by Murodese** [comment]
The first two sets aren't a problem, they're just pre data. The second is a major problem. Is it happening during postproc or scanning?

I have a sneaking suspicion it's due to the use of Barracuda in mysql, but I'll have to investigate more.

**Comment by Murodese** [comment]
```
C:\Python32\lib\site-packages\pymysql\cursors.py:133: Warning: InnoDB: ROW_FORMAT=DYNAMIC requires innodb_file_format > Antelope.
  result = self._query(query)
C:\Python32\lib\site-packages\pymysql\cursors.py:133: Warning: InnoDB: assuming ROW_FORMAT=COMPACT.
  result = self._query(query)
```

:raise:

**Comment by Enverex** [comment]
Postprocessing. It's a completely clean install on MySQL.

**Comment by Murodese** [comment]
Yeah, found the problem. LargeBinary in SQLAlchemy turns into ByteA (nearly infinite size) in Postgres, but BLOB (65kb max) in MySQL.

**Comment by Murodese** [comment]
Go for a clean install - so far as I'm aware, there's no clean way to use alembic to migrate mysql-specific datatypes.

**Comment by Enverex** [comment]
I can just run a query in MySQL to change the type. Originally it was created as a "blob" by PyNab. Is the new one a MediumBlob or LongBlob? (not sure what "Column(LargeBinary((2**32)-1))" translates to).

That said, would I need a clean install to get it to recreate all the broken NZB files properly?

**Comment by Murodese** [comment]
LongBlob. Yeah, the current ones have been truncated and any that were over 65k would be broken.

**Comment by Enverex** [comment]
Trying it now. Something else maybe worth tweaking in future is any columns that will always be positive numeric values should be UNSIGNED, that'll give you pretty much double the maximum value.

**Comment by Murodese** [comment]
We're using SQLAlchemy to handle most database abstraction, and unsigned types don't exist in Postgres. Only one number's gotten that large so far (segments.id), and it's now a bigint so we've got quite a way to go before it gets overflowed.

Let me know how it goes - thanks for the help with debugging, not that many people use MySQL with this so there'll probably be some more weird bugs. These ones popped up because my copy of MySQL was using latin1 as its default encoding, so the keys were never an issue :v

**Comment by th3fallen** [comment]
was this fixed? im still getting the 'Specified key was too long; max key length is 767 bytes' on mysql

**Comment by Murodese** [comment]
Should've been. Which key is complaining?

I still recommend using Postgres, though :)
