### ISSUE TITLE
No Binaries/Releases Being Created

### ISSUE THREAD

**Issue by Enverex** [Murodese/pynab#188]
I've just installed PyNab but I assume I'm doing something silly or have run into a bug as it doesn't seem to be creating any binaries or releases. There's over half a million parts in the database now, but post-processing doesn't appear to be doing anything.

![image](https://cloud.githubusercontent.com/assets/958670/6806633/ca13d3a4-d241-11e4-88be-f72326e8d099.png)

What am I missing here?

**Comment by Murodese** [comment]
Do you have any regexes installed? You either need to put your newznab+ ID in the config to grab their regex or provide your own.

**Comment by Enverex** [comment]
I set up the URL in the config file to use my NN+ ID so it should have been using it. I'm wondering if it was just a temporary issue, as it failed to grab it at the time but it started working randomly an hour or so later.

**Comment by Murodese** [comment]
Possibly. Check if there are any regex in your table: `select count(*) from regexes`, and if not, run `./pynab.py regex` to pull new ones.
