### ISSUE TITLE
Renaming/handling bad releases takes a long time.

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#192]
I noticed consistent periodic spikes in system load since updating to 1.6.0 and managed to track it down to 'resetting unwanted status' eating CPU for 5 minutes solid.

This bit of code in postprocess.py is causing the problem:
```
            # every 25 iterations (roughly), reset the unwanted status on releases
            if iterations % 25 == 0:
                log.info('postprocess: resetting unwanted status')
                db.query(Release).filter(Release.unwanted==True).update({Release.unwanted: False})
                db.commit()
```

I went through my releases table and found 69K rows that are unwanted and would be reset, I don't know if that's a normal quantity, but the deletion of unwanted releases is disabled further down so this number isn't going to decrease (from a cursory scan, the vast majority of those releases look like garbage).

Enabling postgresql statement logging, I get this spamming the log:
```
statement: SELECT files.id AS files_id, files.name AS files_name, files.size AS files_size, files.release_id AS files_release_id 
	FROM files 
	WHERE 255975 = files.release_id
statement: UPDATE releases SET unwanted=true WHERE releases.id = 255975
statement: SELECT files.id AS files_id, files.name AS files_name, files.size AS files_size, files.release_id AS files_release_id 
	FROM files 
	WHERE 255976 = files.release_id
statement: UPDATE releases SET unwanted=true WHERE releases.id = 255976
```

So it looks like query.filter.update is running a select and update for each individual row.

Is there a way to either:
 1. Optimise this update so it takes less time (I expect updating 69K booleans to take much less than 5 mins)

OR

2. Enable the unwanted release deletion again. I'm sure it was disabled for a reason, would be interested in why.

Note: This isn't critical, I have CPU to spare.

**Comment by Murodese** [comment]
Postproc stopped deleting badly-named files (it still deletes passworded/spam files) because we can theoretically rename them later, if appropriate naming is found. Hence, if we add another group predb later, we can rename all of those releases that've been collected previously without having to rescan the group. The unwanted flag is set so that postproc isn't constantly trying to rename 60,000 releases.

That line isn't actually the one causing those queries - setting unwanted to False should only emit a single query. The problem is in manually setting all of them to True after they fail renaming. I'll take a look.

**Comment by Murodese** [comment]
That should alleviate it.

**Comment by gkoh** [comment]
On Tue, 2015-04-14 at 19:29 -0700, James Meneghello wrote:
> That line isn't actually the one causing those queries - setting
> unwanted to False should only emit a single query. The problem is in 
> manually setting all of them to True after they fail renaming. I'll 
> take a look.

Aha, I didn't look properly :(
I did wonder why the performance didn't match the documentation.

**Comment by gkoh** [comment]
On Tue, 2015-04-14 at 19:38 -0700, James Meneghello wrote:
> That should alleviate it.

I've merged it into my installation, give it 25 iterations or so
before I call it good.

Thanks!

**Comment by gkoh** [comment]
It's improved!
That's dropped the processing time from 5 minutes to about 3.5 minutes.
The row by row UPDATEs are now gone, but the row by row SELECTs are still there, I don't know if anything can be done for those.

**Comment by Murodese** [comment]
Can you paste some of the selects?

**Comment by gkoh** [comment]
On Tue, 2015-04-14 at 21:44 -0700, James Meneghello wrote:
> Can you paste some of the selects?

Sure!

```
statement: SELECT files.id AS files_id, files.name AS files_name,
files.size AS files_size, files.release_id AS files_release_id 
        FROM files 
        WHERE 267949 = files.release_id
statement: SELECT files.id AS files_id, files.name AS files_name,
files.size AS files_size, files.release_id AS files_release_id 
        FROM files 
        WHERE 267952 = files.release_id
statement: SELECT files.id AS files_id, files.name AS files_name,
files.size AS files_size, files.release_id AS files_release_id 
        FROM files 
        WHERE 267958 = files.release_id
statement: SELECT files.id AS files_id, files.name AS files_name,
files.size AS files_size, files.release_id AS files_release_id 
        FROM files 
        WHERE 267963 = files.release_id
statement: SELECT files.id AS files_id, files.name AS files_name,
files.size AS files_size, files.release_id AS files_release_id 
        FROM files 
        WHERE 267971 = files.release_id
```

**Comment by Murodese** [comment]
Just to clarify: those are running once every 25 iterations, right? Barring new releases that get picked up. I can entirely disable the unwanted-reset if you want, it's not very useful at the moment.

**Comment by gkoh** [comment]
On Tue, 2015-04-14 at 22:34 -0700, James Meneghello wrote:
> Just to clarify: those are running once every 25 iterations, right? 


I restarted the postprocess to force the unwamted processing, so I'm
pretty sure (the log timestamps all line up).

To absolutely sure, I'll wait for 25 iterations to go before
confirming (that's about 4 hours from now, based on my update
interval).

> Barring new releases that get picked up. I can entirely disable the > unwanted-reset if you want, it's not very useful at the moment.

If it's not currently useful, yeah, disabling would be good.

**Comment by Murodese** [comment]
Done.

**Comment by gkoh** [comment]
On Wed, 2015-04-15 at 15:25 +0930, Guo-Rong Koh wrote:
> On Tue, 2015-04-14 at 22:34 -0700, James Meneghello wrote:
> > Just to clarify: those are running once every 25 iterations, 
> > right? 
> 
> 
> I restarted the postprocess to force the unwamted processing, so I'm
> pretty sure (the log timestamps all line up).
> 
> To absolutely sure, I'll wait for 25 iterations to go before
> confirming (that's about 4 hours from now, based on my update
> interval).

I dug further into my logs, you're right, those SELECTs are running
every iteration, they're not specific to the unwanted release handling.
The log timestamps just happen to look that way, I should be more
careful :(

The interesting part of the postprocess log looks like this:
```
2015-04-15 13:54:30 INFO postprocess: resetting unwanted status
2015-04-15 13:57:58 INFO rename: successfully renamed 0 of 69140
releases and deleted 0 duplicates
```

Somewhere between 'INFO postprocess' and 'INFO rename' there's 3.5
minutes of CPU soaking.

**Comment by gkoh** [comment]
On Wed, 2015-04-15 at 15:39 +0930, Guo-Rong Koh wrote:
> The interesting part of the postprocess log looks like this:
> ```
> 2015-04-15 13:54:30 INFO postprocess: resetting unwanted status
> 2015-04-15 13:57:58 INFO rename: successfully renamed 0 of 69140
> releases and deleted 0 duplicates
> ```
> 
> Somewhere between 'INFO postprocess' and 'INFO rename' there's 3.5
> minutes of CPU soaking.

The remaining time is no longer in the unwanted status handling.
During a non %25 iteration, the logs look like this:
```
2015-04-15 15:42:58 INFO postprocess: deleted 0 passworded releases
2015-04-15 15:46:58 INFO rename: successfully renamed 0 of 69140
releases and deleted 0 duplicates
```

Based on the log message, I assume it's the successful rename of 0
releases that takes 4 minutes (in this particular instance).

**Comment by gkoh** [comment]
Hmmm. Before the first change, I was getting this timing on every iteration:
```
2015-04-15 12:55:10 INFO postprocess: deleted 0 passworded releases
2015-04-15 12:55:11 INFO rename: successfully renamed 0 of 0 releases and deleted 0 duplicates
2015-04-15 12:55:11 INFO rename: successfully renamed 0 of 0 releases and deleted 0 duplicates
```
and this every 25th iteration:
```
2015-04-15 13:00:21 INFO postprocess: resetting unwanted status
2015-04-15 13:04:04 INFO rename: successfully renamed 0 of 69140 releases and deleted 0 duplicates
2015-04-15 13:04:04 INFO rename: successfully renamed 0 of 0 releases and deleted 0 duplicates
```

Now after the change, every iteration looks like:
```
2015-04-15 15:29:23 INFO postprocess: deleted 0 passworded releases
2015-04-15 15:32:55 INFO rename: successfully renamed 0 of 69140 releases and deleted 0 duplicates
2015-04-15 15:32:55 INFO rename: successfully renamed 0 of 0 releases and deleted 0 duplicates
```

So it's gone from eating 3-5 minutes of CPU every 25th iteration to eating 3-4 minutes every iteration.

**Comment by Murodese** [comment]
Oh, I know why.

**Comment by Murodese** [comment]
Try that - it'll be really slow for one iteration, then should be fine after that. Let me know if it keeps trying to scan 69k releases :v

**Comment by gkoh** [comment]
Man, you fix faster than I can report :)

Updated, will report back when it's done stuff.

**Comment by gkoh** [comment]
Confirmed fixed. When there's no additional releases the postprocess iteration now takes about 15 seconds.
Once again, thanks!

**Comment by Murodese** [comment]
Cool!
