### ISSUE TITLE
The API should serve nzb.gz's to save bandwidth and server processing.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#193]
As above. I think all clients support this (sab does, not sure about nzbget?). Newznab decompresses the nzb.gz first, but we don't have to.

**Comment by brookesy2** [comment]
I use nzbget, so if you get something going I can give it a test :)

**Comment by Murodese** [comment]
Try this:

https://gist.github.com/Murodese/1c19e537c1262f36d7c3

**Comment by brookesy2** [comment]
Soooo, im on holiday at the moment and for whatever reason my server has
gone offline :( Will have to wait until next week to test!

**Comment by brookesy2** [comment]
Sorry for the MAJOR delay here. But this does seem to be working for nzbget. I will leave it go a few days and see if anything fails.

**Comment by brookesy2** [comment]
You can probably merge this. I haven't had any issues so far, sonarr has found a few shows from pynab and downloaded via nzbget with no problems.

**Comment by Murodese** [comment]
Yep, just don't have much time atm.

**Comment by brookesy2** [comment]
I will make a PR :)
