### ISSUE TITLE
psycopg2.ProgrammingError: column releases.original_name does not exist

### ISSUE THREAD

**Issue by xsivart** [Murodese/pynab#195]
Just updated this morning:

   a3c8a29..a14d03d  development-postgres -> origin/development-postgres
Updating a3c8a29..a14d03d
Fast-forward
...

and received the following error:
<pre>
INFO  [alembic.migration] Running upgrade 54672c4d904 -> 41996f6d756, change uniques to sha1 keys
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column releases.original_name does not exist
LINE 1: ...me, releases.search_name AS releases_search_name, releases.o...
                                                             ^
</pre>

**Comment by Murodese** [comment]
`./pynab.py update`?

**Comment by xsivart** [comment]
Yep, that is what I was doing :)

Full output here:

https://gist.github.com/xsivart/adf127194366272b71ba

**Comment by Murodese** [comment]
Raaaargh *hulksmashes*

Alembic problem, I'll look into it.

**Comment by Murodese** [comment]
In alembic/env.py, try changing:

```
context.configure(
                connection=connection,
                target_metadata=target_metadata,
                compare_type=True,
                compare_server_default=True
                )
```

to

```
context.configure(
                connection=connection,
                target_metadata=target_metadata,
                compare_type=True,
                compare_server_default=True,
                transaction_per_migration=True
                )
```

**Comment by xsivart** [comment]
Got the same error:

<pre>
INFO  [alembic.migration] Running upgrade 54672c4d904 -> 41996f6d756, change uniques to sha1 keys
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column releases.original_name does not exist
LINE 1: ...me, releases.search_name AS releases_search_name, releases.o...
                                                             ^
</pre>

**Comment by Murodese** [comment]
Try that.

**Comment by xsivart** [comment]
Worked like a charm. Thanks! :)
