### ISSUE TITLE
Alembic 41996f6d756 hangs

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#197]
Unsure if this is hung or just taking forever, the revision looks like its adding/updating some values in the releases table? Postgres looks to be doing stuff, but I am not seeing any changes, been running 4hrs now!

Was this speedy for anyone else?

**Comment by brookesy2** [comment]
Link to revision:

https://github.com/Murodese/pynab/blob/development-postgres/alembic/versions/41996f6d756_change_uniques_to_sha1_keys.py

**Comment by Murodese** [comment]
Might've deadlocked - make sure none of the pynab scripts are running,
restart postgres and rerun the migration.

**Comment by brookesy2** [comment]
Everything was stopped, just restarted and am trying again. Did this take a while for you?

**Comment by brookesy2** [comment]
Going to guess it should be doing:

```
    op.drop_constraint('pres_name_key', 'pres', type_='unique')
    op.create_unique_constraint('pres_uniq', 'pres', ['requestid', 'pretime', 'requestgroup'])
    op.add_column('releases', sa.Column('uniqhash', sa.String(length=40), nullable=True))
    op.drop_constraint('releases_name_group_id_posted_key', 'releases', type_='unique')
    op.create_unique_constraint('releases_uniq', 'releases', ['uniqhash'])
```

fairly quickly? As that is where it looks like its hanging?

**Comment by Murodese** [comment]
It took a little while for me, but not too long. Try using pgadmin and
check server status to see if there are any deadlocks.

**Comment by brookesy2** [comment]
Seems its dying on this, time to investigate:

```
    conn.execute('''
        delete from pres
        where id not in
        (
            select min(id)
            from pres
            group by requestid, pretime, requestgroup
        )
    ''')
```

**Comment by brookesy2** [comment]
Wowsers, locks out the wazoo!

**Comment by Murodese** [comment]
There'll be heaps of locks, but it's the deadlocks that are the problem.
Iirc they're highlighted in red.

**Comment by brookesy2** [comment]
I think I might just manually do the delete then comment it out :)

**Comment by brookesy2** [comment]
Only AccessShareLocks, which from the postgres help don't look like they are deadlocks :( 3 million milis so far!

**Comment by brookesy2** [comment]
@Murodese The friendly people at #postgres helped me out. The query should be:

```
DELETE FROM pres
WHERE id IN (SELECT id
              FROM (SELECT id,
                             row_number() over (partition BY requestid, pretime, requestgroup ORDER BY id) AS rnum
                     FROM pres) t
              WHERE t.rnum > 1);
```

In line with: https://wiki.postgresql.org/wiki/Deleting_duplicates

Only took 10020ms for 1.2m row pre table :) (Was running for 1.4m milis before that lol)

**Comment by Murodese** [comment]
You changed the query and didn't submit a pull request? :p

**Comment by brookesy2** [comment]
I am a bad person :( I will do it today sir!
