### ISSUE TITLE
Some a.b.etc reqs aren't being unhashed.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#199]
The naming scheme changed from REQ: id to just id, so it'll probably need a new regex or something.

**Comment by brookesy2** [comment]
Well ain't that a kick in the pants.

**Comment by brookesy2** [comment]
Was just thinking about this. If we add a regex just for numbers we will get a ton of false positives. Any thoughts on getting around this? Don't want postproc looking forever for a request that may never come :(

Also, are requests themselves posted to a.b.etc? Should we look to try index them?
