### ISSUE TITLE
Parts left mis-match?

### ISSUE THREAD

**Issue by paulouderkirk** [Murodese/pynab#202]
I'm seeing the following log entries:

==> update.log <==
015-05-11 19:18:34 DEBUG binary: saved 59 binaries and deleted 97787 dead parts (0 parts left)...
2015-05-11 19:18:34 INFO binary: processed 10799653 parts and formed 181796 binaries in 64773.09s
2015-05-11 19:18:35 INFO scan: processing releases...

==> stats.log <==
        Parts        |      Binaries       |      Releases       | Other-Misc Releases
 5491880     -97787  |  866818      +42    |  800800       .     |  353572       .

This may be a PEBKAC problem, but why am I seeing "0 parts left" in update.log, but 5491880 parts in stats.log?

**Comment by Murodese** [comment]
Parts left in that log line refers to parts left to process that iteration,
not the actual number of parts left. I'll clarify it :)

**Comment by paulouderkirk** [comment]
Awesome, thank you!  I thought it would be something like that.
