### ISSUE TITLE
nginx and uwsgi.

### ISSUE THREAD

**Issue by Saner2oo2** [Murodese/pynab#207]
hiya. I am haing issues with nginx anf uwsgi, they dont seem towant towork.

nginx loads the default site, but no stats etc...,search wont work.

i tried apache, but that didnt work either (wouldnt even communicate with uwsgi, well didnt seem to anway)

some config files.
uwsgi pynab.ini - http://paste.ubuntu.com/11815949/
nginx conf - http://paste.ubuntu.com/11815955/
wsgi.log - http://paste.ubuntu.com/11815969/

i usedthe guide here

**Comment by brookesy2** [comment]
The issue I usually have with nginx and uwsgi is that the socket path doesn't exist.

Does /var/run/uwsgi/app/pynab/socket exist for you?

**Comment by Saner2oo2** [comment]
yeah, i caught that issue.

I have just been playing, and i install apache, it starts working in nginx (still borked in apache) how strange, but atleast its working.

bizzare

**Comment by brookesy2** [comment]
Other than that I find I have to manually start uwsgi before stuff works. Otherwise my setup is the same as yours :)

**Comment by Saner2oo2** [comment]
closing this as its obviously an issue my end.
