### ISSUE TITLE
API tvsearch by season no longer working

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#211]
Currently running 1.6.1.
This feels a lot like issue #186, not sure how long it's been there, it's a bit different.

Searching by TV season isn't returning the expected results, it returns something (looks like stuff from the latest season), but not what is wanted.

I only discovered this when I tried to backlog something and got zero results.
A manual check of the DB shows they're there, also removing the 'season' filter in the API params shows the items are there.

ie.:
```
 http://yourhost.com/api?apikey=<apikey>&limit=500&t=tvsearch&season=02&rid=<tvshow id>
```
doesn't return season 2 results, but they're there if I do:
```
 http://yourhost.com/api?apikey=<apikey>&limit=500&t=tvsearch&rid=<tvshow id>
```

**Comment by Murodese** [comment]
Regression. Just need to test the fix with Postgres 9.4.

**Comment by Murodese** [comment]
All good.

**Comment by gkoh** [comment]
I just cherry-picked ffb624b60f14fc2594f2034600051ff3384abfe1 into my sandbox, the season search now returns no results at all :(
Although, it does return something if it finds an entire season pack in one nzb ...

**Comment by Murodese** [comment]
Hmm.. seems to be working for me. Did you restart uwsgi?

**Comment by gkoh** [comment]
Yep, I just made sure, before the change, I get some stuff from the latest season, after the change, the same search returns zero results.
However, I did happen to have an indexed 'Season.6' complete, which showed is the only result if I did '&season=6'.
Otherwise, yeah, all empty.
Are there changes in the dev branch that this might rely on? It doesn't seem to be too far ahead of master.

**Comment by Murodese** [comment]
Doubt it, the API rarely changes.

A search on Archer (rid 23354) and season=2 returns the appropriate results. Have you tested a few different shows? Might be a tvrage matching problem with that one show?

**Comment by gkoh** [comment]
OK, that is weird. Archer (rid 23354) works, I'm testing with Doctor Who 2005 (rid 3332).
<insert scratching ...>
Aha, found it, sickbeard is adding the maxage parameter, which has limited the window, removing that makes it sensible again.

Yes, it is fixed, thanks!

**Comment by Murodese** [comment]
Cool :)
