### ISSUE TITLE
What are the minimum system requirements?

### ISSUE THREAD

**Issue by 2devnull** [Murodese/pynab#216]

**Comment by Murodese** [comment]
Too many variables to answer this definitively. People have run it on a raspberry pi (model 1), using fairly conservative memory settings and only indexing a small number of (smaller) groups. It batches well enough that it should run on virtually anything, but if you're indexing a lot of larger groups or groups with larger releases (blurays), it may not keep up with new data. Realistically, it should run fine on something like an N54L or upwards.

**Comment by 2devnull** [comment]
ok, thanks....I was more thinking along the lines of a $5/month 512 MB VPS

**Comment by Murodese** [comment]
512mb of RAM is pretty low and you'd need to do some fairly heavy configuring of both postgres and pynab, but I think it should be possible (if slow).
