### ISSUE TITLE
No releases found, regex problem?

### ISSUE THREAD

**Issue by blindpet** [Murodese/pynab#219]
I am writing a full walkthrough for setting up pynab on ubuntu/debian and I am very close to it working as intended. I am only using a single group teevee. I have backfilled 10 days and am trying to post process but my logs show nothing being done

    2015-10-31 20:00:06 INFO rename: successfully renamed 0 of 0 releases and deleted 0 duplicates
    2015-10-31 20:00:06 INFO rename: successfully renamed 0 of 0 releases and deleted 0 duplicates
    2015-10-31 20:00:06 INFO postprocess: deleting orphan metablacks...
    2015-10-31 20:00:06 INFO postprocess: deleting orphan nzbs...
    2015-10-31 20:00:06 INFO postprocess: deleting orphan nfos...
    2015-10-31 20:00:06 INFO postprocess: deleting orphan sfvs...
    2015-10-31 20:00:06 INFO postprocess: vacuuming relevant tables...
    2015-10-31 20:00:06 INFO sleeping for 300 seconds...

I was under the impression that regex was already included in pynab but maybe i need something else?

Scanning seems to work

    2015-10-31 19:31:07 DEBUG parts: mysql+pymysql insert: 0.01s
    2015-10-31 19:31:07 DEBUG parts: mysql+pymysql insert: 0.13s
    2015-10-31 19:31:07 DEBUG parts: saved 232 parts and 20000 segments in 0.41s
    2015-10-31 19:31:07 INFO group: alt.binaries.teevee: 5399 iterations (107982952 messages) to go
    2015-10-31 19:31:07 INFO group: alt.binaries.teevee: scan limit reached, ending early (will continue later)
    2015-10-31 19:31:20 INFO group: alt.binaries.teevee: scanning group
    2015-10-31 19:31:22 DEBUG server: alt.binaries.teevee: getting range 827186110-827206109
    2015-10-31 19:31:27 INFO server: alt.binaries.teevee: retrieved 827186110 - 827206109 in 5.48s [20000 recv, 564 pts, 0 ign, 0 blk]

**Comment by Murodese** [comment]
There's no regex included by default in pynab. Either you can set your newznab+ ID in the config and it'll automatically grab that and use it, or you can import your own dump from wherever (or create your own!) :)

**Comment by blindpet** [comment]
I feared that, I'm assuming the dump needs to be in sql format, which table does it go in? If you could elaborate a bit that would be great.

I believe nzedb has regexes included (and you don't have to pay), maybe you can get permission to include those?

**Comment by Murodese** [comment]
The import script takes it as CSV (in the format that NN+ provides their regex dumps). At the moment you can change the URL it uses in the config - if you want to load it from a file instead, I can change that with little trouble. If you want to work it manually, it goes in the `regexes` table with very minor modifications from the NN+ dump. See `pynab/util.py:update_regex()` for details.

Possibly. @kevinlekiller, are the regexes in https://github.com/nZEDb/nZEDb/blob/master/resources/db/schema/data/10-release_naming_regexes.tsv free to use?

**Comment by kevinlekiller** [comment]
Yeah, anything written by nzedb is under the GPLv3 (which is not an ideal license, but it was decided for simplicity to keep new code under the same license the original code was using).

The repository nzedb was forked from is GPLv3 licensed and contains a short list of newznab regexes, which could be ok for a few groups, I've never tried personally.

The issue with using the nzedb ones is they are not compatible with newznab I think, although they can probably be converted, possibly programmatically, since going through 100's would be quite an undertaking.

**Comment by blindpet** [comment]
Thank you @kevinlekiller. Can you see what needs to be changed @Murodese to make them compatible? I think it would be great if the config.py included the free nzedb regex by default and adding the newznab+ ones remains optional. Then pynab is completely free to use with complete functionality.

**Comment by Murodese** [comment]
Very little needs to be done. I'll have a look now.

**Comment by Murodese** [comment]
Added. Set the type (nzedb or nn+) and the URL in the config, and the regex script will swap between the collections - it's a bit nightmarish to merge them. Either way, it now defaults to nzedb's collection.

**Comment by Murodese** [comment]
Note that doing this post-install will wipe any regex_id's for releases, which may or may not be a problem.

**Comment by blindpet** [comment]
Excellent. Just to clarify, do I need to point the URL in the config to the nzedb github regex or is this done automatically if the regex url value is empty?

**Comment by Murodese** [comment]
No, if you're not re-copying `config_sample.py` you'll need to add both `regex_type` and the URL to your existing config. The nzedb URL is now the default in the sample config.

**Comment by blindpet** [comment]
Maybe I'm looking at the wrong place then, I'm seeing this in the [sample](https://github.com/Murodese/pynab/blob/master/config_sample.py)

    # regex update settings
        # ---------------------
    
        # regex_url: url to retrieve regex updates from
        # this can be newznab's if you bought plus, include your id, ie.
        # expects data in newznab sql dump format
        # 'http://www.newznab.com/getregex.php?newznabID=<id>'
        'regex_url': '',

    # blacklist_url: url to retrieve blacklists from
        # generally leave alone
        'blacklist_url': 'https://raw.github.com/kevinlekiller/Newznab-Blacklist/master/New/blacklists.txt',
    }

**Comment by Murodese** [comment]
Wrong branch :)

https://github.com/Murodese/pynab/blob/development-postgres/config_sample.py#L288

**Comment by Murodese** [comment]
Now part of `development-postgres`.
