### ISSUE TITLE
Can't Start API on Debian 7

### ISSUE THREAD

**Issue by xvpx** [Murodese/pynab#220]
Can be removed

**Comment by Murodese** [comment]
`sudo chown -R www-data:www-data /var/log/pynab`

**Comment by xvpx** [comment]
I just did that. thanks!

**Comment by Murodese** [comment]
I'll add a note to the readme to that effect.

**Comment by xvpx** [comment]
Thanks, I had already tried to close before you had posted so I appreciate the info either way.
