### ISSUE TITLE
Update nzedb dump update script

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#223]
The url has changed and moved from dropbox:

https://api.github.com/repositories/45781004/contents/dumps

Edit: This is just a reminder for me to do it.

**Comment by brookesy2** [comment]
@Murodese So my fork is filled up with stuff I don't want to PR with this, but here is the fix for this:

https://gist.github.com/brookesy2/9a52bdf0aada9d5b5b57

Thanks!!

**Comment by Murodese** [comment]
Give me a diff or create a new branch and push that PR instead? :) Hard to tell what's changed.

**Comment by brookesy2** [comment]
I was originally committing to the dev-postgres on my fork, so can't branch it :(

Will bust out a diff. But it was a complete re-write of the first function!

**Comment by brookesy2** [comment]
Whipped up a quick PR on a diff org :)

https://github.com/Murodese/pynab/pull/225

I had to replace the file as I did a quick and dirty in vi!

**Comment by Murodese** [comment]
Merged. Thanks :)

**Comment by brookesy2** [comment]
Anytime! :) Hope had phd is doing well!
