### ISSUE TITLE
Use a Bayesian Classifier for categorisation instead of categories.py

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#224]
As above. Need test data to train this properly - my indexer tends to only go for a couple of categories, meaning that if I use my data for testing it'll be really great at classifying movies and TV (but terrible at everything else). If you have a fairly well-rounded releases table, run the below SQL, dump it to CSV and send it to me:

```
SELECT *
FROM (
	SELECT ROW_NUMBER() OVER (PARTITION BY category_id) as r,
	releases.name, groups.name, category_id, parent_cat.name, cat.name
	from releases 
		inner join groups on releases.group_id = groups.id
		inner join categories as cat on releases.category_id = cat.id 
		inner join categories as parent_cat on cat.parent_id = parent_cat.id
) results
WHERE
	results.r <= 1000;
```

...as `tagged_releases_train.csv`, and:

```
SELECT *
FROM (
	SELECT ROW_NUMBER() OVER (PARTITION BY category_id) as r,
	releases.name, groups.name, category_id, parent_cat.name, cat.name
	from releases 
		inner join groups on releases.group_id = groups.id
		inner join categories as cat on releases.category_id = cat.id 
		inner join categories as parent_cat on cat.parent_id = parent_cat.id
) results
WHERE
	results.r > 1000 AND results.r <= 1500;
```

...as `tagged_releases_test.csv`.

Thanks!

**Comment by brookesy2** [comment]
This is badass. Pity, just like you, I only do Movies/TV :(

**Comment by Murodese** [comment]
Used nzb.su data and my own to train it, so for the majority of stuff it's now quite accurate (~95%), more accurate than the existing system. I might put it in a test branch and try it out for a while.

**Comment by brookesy2** [comment]
That is badass!!

**Comment by Murodese** [comment]
This is available in the `newcategorisation` branch if you want to test it.
