### ISSUE TITLE
REQ: and reqid in dev and tvmaze branches

### ISSUE THREAD

**Issue by ukharley** [Murodese/pynab#230]
In pynab.binaries.py name is set to REQ: + reqid:

if match.get('reqid') and not match.get('name'):
     match['name'] = 'REQ: {}'.format(match['reqid'])

but in pynab.requests.py it's querying reqid only, so it fails.

for group, **reg** in GROUP_REQUEST_REGEXES.items():
query = db.query(Release).join(Group).filter(Group.name==group).filter(Release.pre_id == None).\
filter(Release.category_id == '8010').filter("releases.name ~ '{}'".format(**reg**))

I've got mine working by removing REQ: in pynab.binaries.py

**Comment by Murodese** [comment]
That's my bad, I started working with nzedb regex instead (which doesn't use named captures and hence that piece of code never gets used).
