### ISSUE TITLE
backfill errors

### ISSUE THREAD

**Issue by johnavp1989** [Murodese/pynab#231]
I'm seeing various errors when I attempt to backfill.

local socket error (timeout('The read operation timed out',))
nntp error: NNTPTemporaryError('430 No Such Article',)
can't get first date on group, fatal group error. try again later?
could not connect to news server: _ssl.c:584: The handshake operation timed out

I'm using newshosting.

My main concern is that my binaries and release have not increased in a number of days. Status currently looks like this:

```
    Parts        |      Binaries       |      Releases       | Other-Misc Releases │ is not set or incorrect
```

 2173405       .     |   1873        .     |  11808        .     |   244

**Comment by gkoh** [comment]
The timeout is controlled by the 'timeout' parameter in config.py where you specify news server details.
It's measured in seconds and set to 60 by default. You could try increasing that to 120 or larger.
However, if you're timing out after 60 seconds, there's some serious network issues between you and the news server.

**Comment by johnavp1989** [comment]
Yea I'd hate to set that value higher. You got me thinking though... I'm running this behind a VPN and although it's typically a solid connection I've noticed some strange delay when pinging the news server and a high round trip time. I've added a static route for the news server to bypass the VPN and that seems to have resolved those issues. I'll let it run today and see if things improve.

**Comment by Murodese** [comment]
You'll encounter some of those NNTP errors at random depending on your news provider. Some tend to give pretty weird error returns when they don't have a group in retention, for instance. Other times the backfill algorithm just won't like some article numbers - but later when it tries again, it'll take a different path and be fine. If you're getting lots of connection errors though, that'd tend to be either your connection or the news server's (or, as you say, your VPN).

**Comment by johnavp1989** [comment]
Okay so the NNTP errors seems to have decreased dramatically since routing around the VPN. However binaries and release still have not increased. The update.log is going in circles. I see a constant repeat of the same set of binaries being found, then "started pynab logger" followed by "scan: starting update...".  If I left he backfill run long enough it eventually get's into a state where it's waiting for backlog to clear.

**Comment by Murodese** [comment]
Start the scanner without using supervisor `python3 scan.py update` and
you'll get better debug output.

**Comment by johnavp1989** [comment]
This is the output that I got when running the scanner directly:
`/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py:3779 SAWarning: Textual SQL expression on row 'rownum %10000=1' should be explicitly declared as text('rownum %10000=1') (this warning may be suppressed after 10 occurrences) {"exp": util.elipses_string(element)})`

I truncated the segments table before running it and everything seemed to be working properly again until this error. I tailed the update log and found it looping again, stopping on the same binary as it was before I truncated segments.

**Comment by Murodese** [comment]
That's just warning and can be safely ignored. Check the update log
(wherever pynab is logging to) and see if there's more information in
there. Failing that, change the logging level in config.py to debug and
paste the last log output before it crashes :)

**Comment by johnavp1989** [comment]
I'm at a bit of a loss here. I'm already in debug mode but I'm not getting anything informative from the logs. Eventually the update log hits a particular binary and starts looping. It's the same binary each time. Is there a way to trace that binary back to it's source in postgres so I can remove the group that's providing it?

**Comment by Murodese** [comment]
Are you running on the master or dev branch? There was a segfault in an
nzedb regex that might be causing it.

**Comment by johnavp1989** [comment]
Ah yes I see the open issue on it. I am on the developement-postgres branch.

**Comment by Murodese** [comment]
Segfaults are a pain to track down remotely. Do the logs show the binary ID
it's looping on?

**Comment by johnavp1989** [comment]
Not an ID but the name. Here's the tail end of the update log where it begins to loop.

2015-12-14 06:41:50 DEBUG binaries: new binary found: New Age Collection Volume 18 (2015)(320)
2015-12-14 06:41:52 INFO log: started pynab logger
2015-12-14 06:41:52 INFO scan: starting update...

**Comment by Murodese** [comment]
So you can use...

`select * from binaries where name like 'New Age Collection Volume 18%'`

That'll get you what you want. To help me track down the segfault, tell me
which group it's from and also the value of the posted column :)

**Comment by johnavp1989** [comment]
pynab=> select * from binaries where Name like 'New Age Collection Volume 18%';
 id | hash | name | total_parts | posted | posted_by | xref | group_name | regex_id 
----+------+------+-------------+--------+-----------+------+------------+----------
(0 rows)

:-1: 

It seems it's not been inserted into the binaries table. I tried broadening the regex to like 'New%' but still 0 rows.

**Comment by Murodese** [comment]
Oh, try the parts table instead of binaries.

**Comment by johnavp1989** [comment]
One of just many parts. Let me know if you need more details.
Posted: 2015-12-07 20:02:06
alt.binaries.sounds.mp3.new-age

**Comment by Murodese** [comment]
Cheers, I'll get to this soon. If you want to progress, just delete all those parts.

**Comment by Murodese** [comment]
Ok, tried it out:

```
2015-12-15 20:14:03 DEBUG  binaries: new binary found: New Age Collection Volume 18 (2015)(320)
2015-12-15 20:14:03 DEBUG  binaries: new binary found: Dan Gibson's Solitudes - Flute Dreams (2007)(320)
```

So, not a broken regex - works on my machine. Things to try:

- update SQLAlchemy
- update the Regex module
- update PostgreSQL?

**Comment by johnavp1989** [comment]
Thank you for testing it on your machine. I went ahead and deleted all of those parts in an attempt to get it up and running and now the update log looks like this:

2015-12-15 09:14:44 INFO log: started pynab logger
2015-12-15 09:14:44 INFO scan: starting update...
2015-12-15 09:14:54 INFO scan: backlog of segments detected, processing first
2015-12-15 09:14:54 INFO scan: processing binaries...
2015-12-15 09:15:24 INFO log: started pynab logger
2015-12-15 09:15:24 INFO scan: starting update...
2015-12-15 09:15:35 INFO scan: backlog of segments detected, processing first
2015-12-15 09:15:35 INFO scan: processing binaries...

Then I went and upgrade SQLAlchemy from 1.0.9 to 1.0.10 with no change.
I'm already using the latest Regex module.
I'm using the latest version of PostgreSQL from the Ubuntu 14.04 repo 9.4.5-1.pgdg14.04+1

**Comment by johnavp1989** [comment]
Looking at supervisord.log the scan process is clearly segfaulting. Would it be any help to you if I provided the core?

**Comment by gkoh** [comment]
Are you able to provide a backtrace (with gdb) from the core against the python binary? That would narrow the cause.
I recall an issue I ran into earlier this year where an updated module (I think regex, not sure now) was segfaulting.
I ended up reverting the module to a previous version.

(Looking at my package list, regex is at 2015.7.19, which I believe was the last version I found that didn't segfault).

**Comment by johnavp1989** [comment]
I believe I could. Where does pynab drop the core?

I tried rolling back regex to 2015.7.9 as suggested but the result is the same.

**Comment by johnavp1989** [comment]
Prebot is exiting unexpectedly as well.

Traceback (most recent call last):
  File "/home/jpetrini/pynab-master/prebot.py", line 56, in <module>
    main()
  File "/home/jpetrini/pynab-master/prebot.py", line 49, in main
    bot.start()
  File "/usr/local/lib/python3.4/dist-packages/irc/bot.py", line 265, in start
    super(SingleServerIRCBot, self).start()
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 1249, in start
    self.reactor.process_forever()
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 582, in process_data
    self._process_line(line)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 614, in _process_line
    handler(arguments, command, source, tags)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 646, in _handle_message
    self._handle_event(event)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 673, in _handle_event
    self.reactor._handle_event(self, event)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 398, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 1212, in _dispatcher
    method(connection, event)
  File "/home/jpetrini/pynab-master/prebot.py", line 41, in on_pubmsg
    pynab.pre.nzedbirc(a)
  File "/home/jpetrini/pynab-master/pynab/pre.py", line 11, in nzedbirc
    formattedPre = parseNzedbirc(unformattedPre)
  File "/home/jpetrini/pynab-master/pynab/pre.py", line 42, in parseNzedbirc
    if formattedPre['preType'] == "NUK":
KeyError: 'preType'

**Comment by gkoh** [comment]
On Tue, 2015-12-15 at 18:01 -0800, John Petrini wrote:
> I believe I could. Where does pynab drop the core?
> I tried rolling back regex to 2015.7.9 as suggested but the result is
> the same.
> 
> 
> 
>   > 
>   > 

> 
> 

> 


Where the core goes can be highly distribution dependent.
Assuming you have some debugging/system experience, start by checking
the kernel.core_pattern sysctl (or /proc/sys/kernel/core_pattern) and
following the bouncing ball.
Also check your ulimits (ulimit -c), in case that is stopping any cores
at all.

**Comment by johnavp1989** [comment]
No matter how hard I tried I was unable to get this thing to dump a core. I upped my ulimit, tried changing the core path, and followed numerous guides with no luck so I threw up my hands and ended up starting from scratch. I dropped the entire database and changed to the tvmaze branch. So far it seems to be moving along just fine. My problem now is that it seems incredibly slow. At the current rate it could take over a year to build a decent index. It's been running for a week and these are my stats so far:

        Parts        |      Binaries       |      Releases       | Other-Misc Releases │
  27727       +59    |  10023        .     |   4354        .     |   1146        .  

Is there any way I can optimize it?

**Comment by johnavp1989** [comment]
I know I'm going way off track here but another problem I'm having is with log management. I've got logrotate configured for copy truncate but each time it truncates the log prebot dies. I tried copying and replacing the log file instead but this breaks all of the other processes. How do you suggest managing logs?

**Comment by gkoh** [comment]
I use the built-in log rotation, which, by default, rotates logs at 50MB.
It's in config.py under 'log->max_log_size'.

**Comment by johnavp1989** [comment]
@gkoh I hadn't noticed this in the config. I'll remove the logrotate config. Thank you.

**Comment by Murodese** [comment]
> Is there any way I can optimize it?

If you give me a rundown of the server hardware / connection you're running the indexer on, I can certainly make some recommendations. Note that indexing speed is highly dependent on: available bandwidth, available processing resources and the groups that you're indexing. 

Indexing boneless or multimedia takes forever and won't produce too many meaningful results, for instance, while indexing ebooks should only take an hour or so for the entire group. I had to rebuild my index recently, and what I did was activate all the groups I wanted to monitor, and then run backfills on certain groups: teevee (quick and lots of releases), moovee (same deal), hdtv, hdtv.x264, various mp3 groups, etc. These ones are all pretty nicely organised and clean - after a week of indexing, I had ~800k releases and retention on those groups back to around 2100 days. Boneless/multimedia (if you really want to do them) should come last, and expect them to take a really long time to do - probably several months, if you're going back quite a way.

If you're building a new index, I'd also recommend taking the wait times off both scanning and postprocessing - in the config as `update_wait` and `postprocess_wait`. Setting these to 0 means there's no wait period between scans/postproc - which is fine for when you're doing an initial index, but set them to some value more than 0 when it's settled down, as you don't want the indexer repeatedly smashing the news server for updates every quarter second when there are none.

If you have a lot of RAM, you can also up the limits in the scanning config, notably `message_scan_limit` and `group_scan_limit`, as well as increasing `early_scan_threshold` and `binary_process_chunk_size`. The comments give you some idea of what those values can be. Don't forget while backfilling to set `dead_binary_age` to 0, as well.

**Comment by johnavp1989** [comment]
Ok it sounds like it's my strategy then. I just enabled all of the groups and hit go :) I'll narrow it down based on your suggestions and see if that improves things. I've already disabled the wait times but I haven't touched any of the limits. What do you consider a lot of RAM? The system is a VM with 8 cores and 16GB of RAM but I could probably give it a bit more.

**Comment by johnavp1989** [comment]
@Murodese Thanks for the tips! I've followed your suggestions and things have greatly improved and I feel like I'm finally making progress with this. One issue I did discover is that specifying a backfill date fails for certain groups with the following error:

ERROR server: alt.binaries.multimedia.tv: can't get first date on group, fatal group error. try again later?

My workaround has been to just increase the backfill days in the config rather than use the date option which works just as well for me but I figured it was still worth bringing to your attention.

I'm still encountering seg faults on occasion in the same fashion as before. Update reaches a certain binary and bails and restarts never making any further progress. I'll make another attempt to get you a core dump when I have some more time to work on this.

**Comment by johnavp1989** [comment]
@gkoh I still haven't managed to
[gdbcommands.txt](https://github.com/Murodese/pynab/files/76375/gdbcommands.txt)
 get a core dump but I was able to attach gdp to the running process and run a backtrace. I've attached the output. It does look to be a regex issue but I'm not sure how I can narrow down which one.

**Comment by Murodese** [comment]
Those kinds of errors usually indicate a problem with the group on that server (or in general). Sometimes changing news server can fix it (ie. supernews's US server to EU or the like), sometimes it's temporary, sometimes the group is just dead.

The segfaults usually indicate a problem with a cpython module (ie. regex, lxml). Unfortunately they're a huge pain in the ass to track down, particularly if they can't be replicated (often due to system configurations). 

That's definitely a regex segfault. Give me a minute to see if I can get it. Which regex set are you using - nn+ or nzedb? (default is nzedb)

**Comment by Murodese** [comment]
Hm, there's only two nzedb regex that apply to that binary:

`^\[\d+\]-\[.+?\]-\[.+?\]-\[ (?P<match0>.+?) \]-\[\d+\/\d+] - ".+?" yEnc$`

and

`^\[:.+:\]\[FLAC.+\]-\[:(?P<match0>.+):\]-\[\d+\/\d+\]-".+" yEnc$`

The binary matches the first one without issues on my laptop, which is all I have here at the moment. Try running the following just in a Python terminal:

```
>>> import regex
>>> subj = '[66224]-[FULL]-[#a.b.flac@EFNet]-[ The_Light_Of_Saba-Thy_Kingdom_Come_Bw_Solitude-(KCS004)-7INCH_VINYL-FLAC-2007-YARD ]-[06/14] - "00-the_light_of_saba-thy_kingdom_come_bw_solitude-(kcs004)-7inch_vinyl-flac-2007-yard.sfv" yEnc'
>>> reg = '^\[\d+\]-\[.+?\]-\[.+?\]-\[ (?P<match0>.+?) \]-\[\d+\/\d+] - ".+?" yEnc$'
>>> r = regex.search(reg, subj)
>>> r
<regex.Match object; span=(0, 226), match='[66224]-[FULL]-[#a.b.flac@EFNet]-[ The_Light_Of_Saba-Thy_Kingdom_Come_Bw_Solitude-(KCS004)-7INCH_VINYL-FLAC-2007-YARD ]-[06/14] - "00-the_light_of_saba-thy_kingdom_come_bw_solitude-(kcs004)-7inch_vinyl-flac-2007-yard.sfv" yEnc'>
```

**Comment by johnavp1989** [comment]
I'm using nzedb. Below is the output from the terminal. Seems to have matched.

>>> import regex
>>> subj = '[66224]-[FULL]-[#a.b.flac@EFNet]-[ The_Light_Of_Saba-Thy_Kingdom_Come_Bw_Solitude-(KCS004)-7INCH_VINYL-FLAC-2007-YARD ]-[06/14] - "00-the_light_of_saba-thy_kingdom_come_bw_solitude-(kcs004)-7inch_vinyl-flac-2007-yard.sfv" yEnc'
>>> reg = '^\[\d+\]-\[.+?\]-\[.+?\]-\[ (?P<match0>.+?) \]-\[\d+\/\d+] - ".+?" yEnc$'
>>> r = regex.search(reg, subj)
>>> r
<regex.Match object; span=(0, 226), match='[66224]-[FULL]-[#a.b.flac@EFNet]-[ The_Light_Of_Saba-Thy_Kingdom_Come_Bw_Solitude-(KCS004)-7INCH_VINYL-FLAC-2007-YARD ]-[06/14] - "00-the_light_of_saba-thy_kingdom_come_bw_solitude-(kcs004)-7inch_vinyl-flac-2007-yard.sfv" yEnc'>

**Comment by Murodese** [comment]
I'll test this more thoroughly when I get home in a few days and actually pull the a.b.m.flac group.

**Comment by johnavp1989** [comment]
Thanks! Enjoy your time your time away!

**Comment by gkoh** [comment]
@johnavp1989 If you are able to run the process in gdb from the start, it will drop to an interactive session when it crashes.
Or is that backtrace the result of such a thing?

**Comment by johnavp1989** [comment]
@gkoh I waited for a crash for the current process and then attached as soon as a new process spawned so this should encompass the eventual crash of the new process but to be sure I will do as you suggested later today and post the output here.

**Comment by BitterMelon** [comment]
I'm having the same problem. I had it yesterday running MariaDB*, and again today after resetting and re-running with Postgresql. Removing the parts related to the last logged binary didn't help, and it's not the same one yesterday and today. Feels like the culprit may be the next line that never gets logged maybe?

I'm running this on a VMware vm, Ubuntu 14.04 LTS, everything up to date (PSQL 9.3, Python 3.4.3, SQLAlchemy 1.0.11).

*This btw needed a small SQL syntax patch in pynab/requests.py:

`filter(Release.category_id == '8010').filter("releases.name ~ '{}'".format(reg))`
=>
`filter(Release.category_id == '8010').filter("releases.name REGEXP '{}'".format(reg))`

**Comment by jamesmeneghello** [comment]
Same as for #262: try installing regex version 2.4.44.
