### ISSUE TITLE
Scalable backend

### ISSUE THREAD

**Issue by kalw** [Murodese/pynab#232]
Hi there,

Due to the incredibly large amount of data that we can deal with wide indexation, would not it be lovely to be able to extend backend with engine like https://crate.io or Elasticsearch ?
Regarding Crate, there seems to exist python client (https://github.com/crate/crate-python) ;  someone would be able to look at the eventuality ?

Regards,

-- 
Regis A. Despres

**Comment by brookesy2** [comment]
I have been using ES for my logs, its pretty handy. Would be great to expand it though :)

**Comment by Murodese** [comment]
I use ES in other projects, but I'm not entirely sure it'd be that useful here. I originally moved away from Mongo for a specific reason that'd also cause problems under ES (maintenance was a nightmare without relationships between certain entities). There's also no performance problems under Postgres (though MySQL still sucks), so I'm not sure what advantage there'd be.

**Comment by kalw** [comment]
Then I'll try if Pynab fit into cities-db =)
