### ISSUE TITLE
Taming the branches (merging)?

### ISSUE THREAD

**Issue by boo1234** [Murodese/pynab#238]
I was on the dev-postgres branch for quite a while, but nothing appeared to be working (the occasional tv ep would download), but then I noticed talk of broken tvrages, new tvmaze branch, etc. It's hard to know what branch should be used. 

I gather from a quick scan of issue conversations that most branches seem to be experiments - would it be possible to simplify things, deprecate some older branches (tag them), etc? We could then make `master` the stable branch and a `develop` the pre-stable branch (ie. bleeding edge folks could be testing against it).

Topic branches would be created off of `develop` when fine folk like @brookesy2 want to add/improve functionality. After review, those branches would be 'rebased' (ensured up to date with the latest `develop` branch) then merged back into `develop`, ready for bleeding edge testing.  

See http://nvie.com/posts/a-successful-git-branching-model/#the-main-branches for more information on this development model. It doesn't have to be super formal, of course. But this lends some predictability to the project.

**Comment by Murodese** [comment]
That's actually the model this project follows, it's more just that we've been down the rabbit hole a bit. The TVRage death necessitated a major rewrite in a different branch, and I've been waiting until that's been tested more thoroughly before merging that back into dev. Once that's happened, I'd merge it back to master and it'd be back to semi-organised. That's probably going to happen this week sometime - I'm finally on holidays for a couple weeks, so I have a bit of time to sort shit out.

Some of the other branches (`plpython` for instance) are genuinely experiments and are really old branches not intended for use, but the code is useful to keep around.

**Comment by Murodese** [comment]
Partially cleaned up. I'll let people update the dev branch and test the conversion stuff for the genericid changes and if that's all fine, I'll push it to master.
