### ISSUE TITLE
new install, predb issues?

### ISSUE THREAD

**Issue by boo1234** [Murodese/pynab#240]
Starting from scratch after recent changes/merges by @Murodese to the `dev-postgres` branch - I'm seeing this:

```
Building tables...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> b82b375466
Installing admin user...
Copying groups into db...
Copying categories into db...
Copying TV data into db...
Copying movie data into db...
Updating regex...
Updating binary blacklist...
Copying pre data into db...
Problem inserting data into database: 'module' object has no attribute 'processNzedbPre'
```

That last line looks... like a bug?

**Comment by boo1234** [comment]
For what it's worth, I ran the script manually on the command line like so:

```
python3 scripts/nzedb_pre_import.py large
```

and it appears to be doing something...

**Comment by johnavp1989** [comment]
I ran into this same issue with a fresh install just last week. However I also haven't had any issues so far.

**Comment by Murodese** [comment]
Regression, I think. You can safely ignore it for the moment and use the
console.

**Comment by boo1234** [comment]
Should the `large` or `small` predb command be used?

**Comment by brookesy2** [comment]
Large will download a massive initial import. Small will pull down the
daily pre csv's. If you have a good connection go large and then small :)
