### ISSUE TITLE
Implement some sort of date based expiration to limit database

### ISSUE THREAD

**Issue by Herkemer** [Murodese/pynab#241]
Unless I'm completely missing it, there is currently not a way to limit the data based based on date (ie keep the last 120 days of releases).

Posting an issue to illicit feedback on such a feature, so feel free to weigh in on if this would be useful, how it should work, etc etc.

**Comment by brookesy2** [comment]
Could possibly add something to postproc that removes older data. Then just have a config setting to let you change the number of days.

**Comment by Herkemer** [comment]
That's what I did, right before the various orphan deletes are done.  Seems to be working so far, I've run a few tests, but want to set it up and let it run a little while before pushing out a PR.

**Comment by brookesy2** [comment]
Sounds good to me! Happy new year :)
