### ISSUE TITLE
Duplicate key running upgrade script for generic id support

### ISSUE THREAD

**Issue by Herkemer** [Murodese/pynab#242]
Seems like I've gotten unlucky when upgrading my database:

IMDB: Miller's Crossing (100150) -> 17765
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(17765) already exists.

Indeed I do have an entry with the IMDB id:
pynab=> select * from movies where id = '17765';
  id   |  name   |         genre          | year 
-------+---------+------------------------+------
 17765 | College | Drama, Comedy, Romance | 1927
(1 row)

**Comment by Murodese** [comment]
Fairly lengthy pain in the ass debugging this for when I was going through
mine, didn't come up with a definitive answer. I think it was some broken
records from a previous import, so maybe just delete the complaining rows
and let them re-process later? Hopefully should only be a couple.

**Comment by Herkemer** [comment]
Yeah, I'm doing a little sleuthing and it's possibly going to be a bigger issues than I thought:

pynab=> select id from movies where id like '17%';
   id    
---------
 17136
 17423
 17765
 17825
 17925
 170016
 170180
 170691
 170982
 171580
 171612
 171804
 
Would it work to loop over all entries and add some sort of prefix, and then do the conversion?

I'll try removing entries as I hit them and see how far I can get before giving up :)

**Comment by Murodese** [comment]
Do most of the other ids start with tt?

**Comment by Herkemer** [comment]
Yes, but I've got 13k+ that don't.

**Comment by Murodese** [comment]
They're the ones causing the problem. Maybe two step: add tt to the start
of those that don't have it already, then do the conversion.

**Comment by Herkemer** [comment]
Ok, not totally satisfied with this but it seems to be working, I've got 400k+ movies so it's going to be running awhile, it at least got past the first couple of dupes I was noticing.  If this is acceptable I'll submit a PR, otherwise, I'll implement the two step thing.

--- a/alembic/versions/3bc50ecd0bb_add_generic_id_support.py
+++ b/alembic/versions/3bc50ecd0bb_add_generic_id_support.py
@@ -52,6 +52,13 @@ def upgrade():
 
     print('Starting ID conversion.')
     for show in bind.execute(tvshows.select().order_by(tvshows.c.id)):
+        new_id_ok = False
+        while not new_id_ok:
+            if bind.execute(tvshows.select(tvshows.c.id == i)).first():
+                print('Found dupe id, incrementing new id')
+                i += 1
+            else:
+                new_id_ok = True
         try:
             print('TVRAGE: {} ({}) -> {}'.format(show[tvshows.c.name], show[tvs
         except:
@@ -72,6 +79,13 @@ def upgrade():
         i += 1
 
     for movie in bind.execute(movies.select().order_by(movies.c.id)):
+        new_id_ok = False
+        while not new_id_ok:
+            if bind.execute(movies.select(movies.c.id == str(i))).first():
+                print('Found dupe id, incrementing new id')
+                i += 1
+            else:
+                new_id_ok = True
         try:
             print('IMDB: {} ({}) -> {}'.format(movie[movies.c.name], movie[movi
         except:
