### ISSUE TITLE
Request ID too large when processing requests during postprocessing

### ISSUE THREAD

**Issue by Herkemer** [Murodese/pynab#244]
When parsing a request for a release that has a name that ends up being a LARGE number (ie 6453253720) it generates invalid SQL because the number if larger than the integer value:

```
2015-12-31 22:40:33 CRITICAL Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: value "6453253720" is out of range for type integer
LINE 3: ...252753', '248335', '3535206', '253083', '247146', '645325372...
                                                             ^
```

Here is the SQL that produced the error:

```
 [SQL: 'SELECT pres.id AS pres_id, pres.pretime AS pres_pretime, pres.name AS pres_name, pres.searchname AS pres_searchname, pres.category AS pres_category, pres.source AS pres_source, pres.requestid AS pres_requestid, pres.requestgroup AS pres_requestgroup, pres.filename AS pres_filename, pres.nuked AS pres_nuked \nFROM pres \nWHERE pres.requestgroup = %(requestgroup_1)s AND pres.requestid IN (%(requestid_1)s, %(requestid_2)s, %(requestid_3)s, %(requestid_4)s, %(requestid_5)s, %(requestid_6)s, %(requestid_7)s)'] [parameters: {'requestgroup_1': 'alt.binaries.teevee', 'requestid_4': '253083', 'requestid_6': '6453253720', 'requestid_3': '3535206', 'requestid_1': '252753', 'requestid_7': '252005', 'requestid_5': '247146', 'requestid_2': '248335'}]
```

**Comment by Herkemer** [comment]
Thinking that adding a simple isinstance check to make sure the request id is an integer, and ignoring if it's not might be ok, but I'm not familiar enough with what all this code is doing to be sure.

**Comment by Murodese** [comment]
I remember recently fixing a bug similar that should be in the dev branch at the moment, have a look in the commit history? I'll take a look at it in a couple days, on holidays ATM.

**Comment by Herkemer** [comment]
I think I'm running the latest, the regex allows a 10 digit number.  Postgres integer is limited to 2147483647 and I was having an issue with 6453253720.  Maybe expand the regex to allow 9 digits with some additional fancy regex to get to the rest.

Alternative would be to change requestid to be a bigint, then it probably won't be a problem.

**Comment by Murodese** [comment]
The request IDs are all pretty small though (a.b.teevee is up to the mid 200k's iirc), so anything into bigint territory isn't going to be a request ID anyway. Maybe limit it to 8 digits, which'll keep us going for at least a few decades.
