### ISSUE TITLE
Bayesian categoriser needs python 3.4 due to pickle protocol version.

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#251]
I was running python3.3, but upon upgrade to master with the Bayesian categoriser, the scanner fails to run with:
```
    CATEGORISER = pickle.load(open(os.path.join(root_dir, 'db/release_categoriser.pkl'), 'rb'))
ValueError: unsupported pickle protocol: 4
```

A bit of googling shows protocol 4 was added in python 3.4.
Either we require people to upgrade to python 3.4, or recreate the pickle with protocol 3 by setting the highest_protocol.

I have upgraded to python 3.4, no biggie.

**Comment by Murodese** [comment]
Thanks for these! I'll chuck it on protocol 3 - I don't think there's much new in 4.

**Comment by gkoh** [comment]
Thanks for fixing so quickly!
All looks good on this end now :)
