### ISSUE TITLE
Alternate pynab search GUI (not an issue)

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#253]
After fighting (and failing) to build the pynab GUI (I use an esoteric OS), I set out to create my own, since the requirements were fairly basic.
Some collaboration with a friend resulted in a GUI that also supports some integration with SABnzbd.
Technically the GUI can talk to any NN+ API compliant service, but has only been used with and developed for pynab.

The GUI is pure client side JS, installation is simple, checkout, change pynab URL, configure web server to serve it somewhere.

Any comments welcome:
https://github.com/gkoh/pynab_search

**Comment by brookesy2** [comment]
Awesome stuff, will take a look :)

**Comment by jamesmeneghello** [comment]
That looks great! I'll test it out in a few days (I had a quick look, but my indexer web config is a little complex so I can't test it yet).

The one I did was really quick and is based on old angular that probably doesn't even build anymore, so any replacement is recommended. If this works well I'll cut the webui out of pynab and just link to yours for people that want it.

**Comment by jamesmeneghello** [comment]
Sorry, getting absolutely smashed at the new job. I'll get to this eventually :)

**Comment by gkoh** [comment]
No worries, not urgent whatsoever.

**Comment by JameZUK** [comment]
Hi gkoh, I tested this and its great. Thanks :)

**Comment by gkoh** [comment]
@JameZUK thanks for trying it out!
Good to hear it works for you.
