### ISSUE TITLE
prebot unable to join channel

### ISSUE THREAD

**Issue by Herkemer** [Murodese/pynab#255]
Haven't had a chance to do much debugging, still looking, mostly just wanted to push out an issue to see if anyone else has seen the same thing.

Symptoms are, prebot.py starts up, looks like everything is fine, but never logs a message.  When I do a /whois on the generated nick I see it on the server but it's not joined to any channels.

If I change the channel name to something else, it joins that channel just fine.

**Comment by jamesmeneghello** [comment]
@brookesy2: Channel private or invite-only or something? I don't follow the IRC at all.

**Comment by Herkemer** [comment]
I'm able to join myself using irssi, but perhaps there are some permissions that keep something like a bot from joining.  I'm not familiar enough with IRC to know for sure.

**Comment by Herkemer** [comment]
Ok, channel is secret, that explain why it's not showing via /whois.  Now, how to determine if it actually did join and why am I not able to on_pubmsg fire?

**Comment by brookesy2** [comment]
They are touchy with join/parts and will ban you. If this happens you have
to fall back to the import script using the "small" argument.

Would be good if we could find a few other chans. If anyone knows any I can
add them in.

**Comment by Herkemer** [comment]
Ugh, yep I am banned, thanks for the hint @brookesy2.  Need to learn to turn off prebot when I'm doing a lot of development, too much up/down I guess.

Closing, doesn't appear to be a problem.  I'll run the import script.

**Comment by kevinlekiller** [comment]
@Wally73 brought this up on IRC, he mentioned this line creates random users names: https://github.com/Murodese/pynab/blob/master/prebot.py#L46

Which we don't ban for, but we ban if the name is random and logs in / out multiple times in a quick succession.

We had people doing this maliciously using botnets (we assume - since there were dozens), they were logging in and out 100's of times per minute with the same host name but different user name, for weeks (until we started banning).

**Comment by brookesy2** [comment]
@kevinlekiller Ok, that is amazing news. Perhaps we can just move this to config and set a "bot_name" setting that people can update?

I can probably write this up this weekend.

@Murodese Thoughts?

**Comment by Wally73** [comment]
you can set up pre channel your self 
source of the irc bots https://github.com/nZEDb/nZEDb_IRC_Bots

**Comment by kevinlekiller** [comment]
@brookesy2 Yeah, that's what nzedb does, there's a config with a user name, it's a bit of a hassle, since if the username is taken it won't connect, but many of them register their nicks and/or have znc servers also to alleviate that.

**Comment by brookesy2** [comment]
@Wally73 Thanks a lot for this, it is amazing :) I will have a read through and get this going. Apologies for inconvenience!!

Edit: Quick fix is to allow bot names, second I will look to see if we can host our own channel!

**Comment by kevinlekiller** [comment]
We don't mind if you use our channel, it's already set up, so it saves you extra hassle.

**Comment by brookesy2** [comment]
@kevinlekiller Amazing, thank you!! Again apologies for any inconvenience caused.

**Comment by Wally73** [comment]
Let me know when this is merged so that i can remove a few bans ;)

**Comment by brookesy2** [comment]
@Wally73 The merge has been done. Can't thank you guys enough!!

**Comment by jkruse** [comment]
I just ran into this issue. I updated to the fixed version but my IP is already banned. How to get unbanned? @Wally73 can you help?

**Comment by Wally73** [comment]
PM me on IRC with the bots hostmask then i can unban it ,

**Comment by jkruse** [comment]
Thanks, already did ;)

**Comment by Irocanme** [comment]
Not sure if this an issue but the past 2-3 days i keep seeing in my prebot logs from time to time the following error:

> 2016-03-23 18:13:22 DEBUG pre: Error parsing nzedbirc - 'NoneType' object has no attribute 'groupdict'

The error is quit common in the logs. Sometimes every 2-3 mins.
I'm on the development-postgres branch so that I can actually use the prebot script. 

Is this a sign of a minor/major issue or it's just some debugging info?

**Comment by brookesy2** [comment]
Hrmm, the bot doesn't actually die each time though right? I added some
code to catch this error a while ago. Essentially it just means it couldn't
parse the line of text from IRC.

**Comment by brookesy2** [comment]
@Irocanme Just checked my logs, yeah its just a non suppressed error. I will update the code to make it look less bad :)
