### ISSUE TITLE
Three iterations max?

### ISSUE THREAD

**Issue by jkruse** [Murodese/pynab#263]
What's going on in groups.py line 123? Enabling a new group will start loading articles just fine, but after three iterations (60k) articles it aborts. On next update only new articles since last scan seem to load (it doesn't start from where it aborted).

**Comment by jkruse** [comment]
(on dev branch)

**Comment by jamesmeneghello** [comment]
Good question. I'll fix that later.

**Comment by ghost** [comment]
Could this cause gaps in the scan process - missing parts/releases or something?

**Comment by jamesmeneghello** [comment]
No, it'll just mean that on the very first scan of a group it won't go back as far as specified in the config. If you then backfill it'll continue backwards as appropriate.
