### ISSUE TITLE
Ubuntu 14.04 installation tips

### ISSUE THREAD

**Issue by JameZUK** [Murodese/pynab#264]
I had some irritating issues installing pynab on Ubuntu 14.04. The instructions on the front page miss several python modules and there is also an irritating conflict with the six module that is installed on the base Ubuntu python build.

This issue only presented itself with a highly frustrating error when trying to start the prebot. The error inside supervisor looks like: pynab:prebot: ERROR (abnormal termination)

To fix it, just remove six from the base Ubuntu install and force pip3 to upgrade it to the latest version:

> sudo rm /usr/lib/python2.7/dist-packages/six.pyc
> sudo rm /usr/lib/python2.7/dist-packages/six.py
> sudo rm -rf /usr/lib/python2.7/dist-packages/six-1.5.2.egg-info
> sudo pip3 install six --upgrade

There are also some missing modules (I think this is all of them):

> sudo pip3 install jaraco.itertools
> sudo pip3 install jaraco.collections
> sudo pip3 install jaraco.text

Hope this helps someone!

Pynab is fantastic, so so much faster and lighter than newzbab. Nice work :)

**Comment by brookesy2** [comment]
It is odd for those jaraco ones, as they usually come with the main package. Very weird! Thanks for documenting it all!! :)

**Comment by JameZUK** [comment]
Not a problem, thanks for all the hard work ;-)
