### ISSUE TITLE
TVRage data needs update, also import issues?

### ISSUE THREAD

**Issue by ghost** [Murodese/pynab#285]
I noticed this due to the show @Midnight. Do a search in your releases for At.Midnight.2016.05.12.720p.HDTV.x264-YesTV which was posted to a.b.teevee

This show is not being identified as it's not even in the tvshows table. On the TVRage site it's at http://www.tvrage.com/shows/id-38478

It looks like the tvrage.json dump only goes to show 37849. However, my database table only has ~15,000 rows so it's not fully imported for some reason. Either way, the dump is a bit behind. Is there a way to automate the tvrage data so it's as recent as possible in the database?

**Comment by ghost** [comment]
I added it to the database myself and tried to run quick_postprocess.py but that appears to be broken

```
# python3 ./scripts/quick_postprocess.py 
This script will attempt to post-process releases against local databases.
After importing or collecting a large batch of releases, you can run this once prior to start.py.
This will check all local matches first, leaving start.py to just do remote matching.
It'll really just save some time.

To continue, press enter. To exit, press ctrl-c.
/usr/local/lib/python3.4/site-packages/sqlalchemy/sql/elements.py:3778: SAWarning: Textual SQL expression 'rownum % 10000=1' should be explicitly declared as text('rownum % 10000=1') (this warning may be suppressed after 10 occurrences)
  {"expr": util.ellipses_string(element)})
```

**Comment by ghost** [comment]
I also verified the length of the tvrage.json dump and see it's not supposed to produce as many rows as the id numbers would lead you to believe, so my import wasn't quite as messed up as I thought.

**Comment by ghost** [comment]
I restored from database backup and quick_postprocess.py is working now. Something went very wrong when I truncated those tables and tried to reload them.

I did more closely examine the schema and correctly add the "At Midnight" show to tvshows and dbid tables, but it doesn't seem it helped because it still wasn't found after a run of quick_postprocess.py. I saw the shows in the log saying they didn't match any show regex. I've tried both nn+ and nzedb regex with no luck so I might have to write my own for this show.

**Comment by gkoh** [comment]
I'm fairly sure we migrated over to tvmaze after the tvrage outage last year, see #215.
Of course, if the show ID is missing, that's still a problem.
Which it is:

```
# select name,tvshow_id from releases where name ~* 'at.midnight.2016.05.12';
                    name                     | tvshow_id 
---------------------------------------------+-----------
 At.Midnight.2016.05.12.HDTV.x264-YesTV      |          
 At.Midnight.2016.05.12.720p.HDTV.x264-YesTV |          
(2 rows)
```

Actually, it is in my tvshows table:

```
# select * from tvshows where name ~* '@midnight';
  id   |   name    | country 
-------+-----------+---------
 15816 | @Midnight | US
(1 row)
```

or perhaps:

```
# select * from tvshows where name ~* 'at.midnight';
  id   |    name     | country 
-------+-------------+---------
 18742 | At.Midnight | 
(1 row)
```

@ vs 'At' looks like a potential problem, I'm not familiar with this part of pynab, others will need to weigh in.

**Comment by brookesy2** [comment]
@gkoh Correct, moved to tvmaze after issues with tvrage. Though the updates let us support many sources.
