### ISSUE TITLE
Prebot script not working?

### ISSUE THREAD

**Issue by rembo10** [Murodese/pynab#290]
Hey - I just switched to the development version and noticed I'm not getting anything in the logs for the prebot. I put my nick into the config....  and I see in the log:
"2016-09-09 20:27:03 INFO Pre: Bot Nick - <mynick>"
But I notice that there's nothing getting inserted. Is there anything I'm missing?

**Comment by brookesy2** [comment]
@rembo10 More than likely it hasn't connected or the configuration is wrong. What do you have listed in config.py?

**Comment by rembo10** [comment]
Just added my nick. Do I need to register it or something?

**Comment by brookesy2** [comment]
Nope, it should connect automatically. If it doesn't it probably means there is some issue connecting to the IRC server. Can you try connect yourself using another client? Just to make sure your IP isn't g/k-lined or some such.

**Comment by rembo10** [comment]
Oh yeah, it's a problem on my end. Thanks for the quick replies!

**Comment by brookesy2** [comment]
No problem. Thanks for resolving this one :)

**Comment by rembo10** [comment]
Just a quick question: I think maybe I got banned from #nzedbpre for having
a random nick from the master branch (I can't think of what else it might
be). Do you know the best way to resolve that?

**Comment by brookesy2** [comment]
Hrmm its kind of difficult. If you cycle your connection you should be allowed to join. There is a banner message in the chan for pynab people that says who you can message to get unbanned, I have forgotten their name :(

**Comment by rembo10** [comment]
Hmm ok. I'll give it a day to see if it changes otherwise Ill try to get in
touch with them.  Thanks for the help!

**Comment by brookesy2** [comment]
No problem :)
