### ISSUE TITLE
Rar Parsing Occasionally Overflows Release Size Column

### ISSUE THREAD

**Issue by NeilBetham** [Murodese/pynab#302]
I've been running into some issues in post processing recently with rar parsing specifically. There seems to occasionally be issues where the parsing of a rar is overflowing the max size of a big int column in postgres. I'm not quite sure where the issue is coming from, my best guess is probably a malformed rar file. In any case the best solution I can think of is to check if the size is greater than or equal to the overflow and set it to 0; I find it very hard to believe any upload would be pushing 9 exabytes. Thoughts? If people are cool with that I can add a fix for this.

**Comment by gkoh** [comment]
This looks like #280 as the primary cause.
Of course, doing a size check is a good defense against other unknown weird stuff in our rar library.

**Comment by brookesy2** [comment]
@gkoh  Was just going to say this looked like what you mentioned earlier :) Thanks for chiming in!-

**Comment by NeilBetham** [comment]
Ah, sorry for the dupe. I will close this and move discussion to the other bug.
