### ISSUE TITLE
Add 'supportedparams' in caps

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#307]
I recently had an issue where SickRage was not able to find some slightly older TV shows (about a year old).

After a bit of debugging, I found SickRage was searching with a query param that we don't support, 'tvdbid'.
It looks like SickRage is now only searching by this ID, along with season and episode filters.
Recent shows are being found as pynab ignores the tvdbid param, but filters on season and episode, and these usually fit inside the search limit. (eg. If I search for show XYZ, season 1, episode 4, pynab returns all releases for anything season 1, episode 4).

I'm just testing a fix now where we specify only the capabilities in the caps page (and don't support tvdbid).
This seems to make SickRage issue a text search like it I expected it to.

Perhaps we can consider adding in support for 'tvdbid' as a separate issue.

**Comment by brookesy2** [comment]
I guess the issue is SickRage wasn't originally supported. Will this change fully support it?

**Comment by gkoh** [comment]
Well, it works for everything I need now, so I'd say yes.
