### ISSUE TITLE
Fewer releases being found recently.

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#314]
Hello all,

Recently I've noticed the number of releases pynab is finding very low.
I note that some of the other indexers (based on nzedb) are picking up things that pynab isn't seeing.
I have confirmed everything appears to be working (prebot, postprocess, etc).

Has anyone else experienced this or have tips on how to find the problem?

**Comment by gkoh** [comment]
After a little bit of poking around, this seems very strongly related to #311.

**Comment by brookesy2** [comment]
@gkoh Yeah that and also omdb went private. Working on going back to tmdb, but requires people to get a free api key.

**Comment by gkoh** [comment]
@brookesy2 thanks for that.
We need to revive this project if possible, I don't really want to run a PHP/MySQL solution if I can avoid it.

**Comment by brookesy2** [comment]
@gkoh Yeah, I been trying to put time into adding support for omdb and tmdb again with api keys. Hopefully have something to show for it. (Don't know when then!)

**Comment by brookesy2** [comment]
@gkoh I have added some highly experimental support for omdb and tmdb with api keys. I will check in a branch and let you know so you can test also. These require you to sign up with tmdb (free key), and omdb (paid key $1/mo).

**Comment by brookesy2** [comment]
@gkoh https://github.com/brookesy2/pynab/tree/omdbtmdb

**Comment by brookesy2** [comment]
Dupe of #309
