### ISSUE TITLE
Building WebUI on Ubuntu 14.04

### ISSUE THREAD

**Issue by easyroot** [Murodese/pynab#74]
- After (or during) installing npm, the command node is not available; I fixed this by install the package nodejs-legacy but I don't know if this causes any problems
- I ran npm install, but afterwards bower and grunt wasn't found (I fixed this by installing bower and grunt-cli as root to /usr/local)
- Finally, when running grunt build, I had to install a lot of packages by hand (not as root so it seems to have installed the packages in the build tree)

Now I'm stuck at this:

Loading "grunt-karma.js" tasks...ERROR

> > TypeError: Object function createServer() {
> >   function app(req, res, next){ app.handle(req, res, next); }
> >   merge(app, proto);
> >   merge(app, EventEmitter.prototype);
> >   app.route = '/';
> >   app.stack = [];
> >   return app;
> > } has no method 'json'

**Comment by patilms16** [comment]
Hello,
I am trying to setup grunt-karma framework on windows. 

I have installed all required latest dependencies using npm install.

However once I run grunt test, getting error function 'createServer' has no method 'json'.

Please suggest how can I resolve this issue?

**Comment by Murodese** [comment]
I don't think you need to use test - from memory, you use `grunt build` and/or `grunt serve` or `grunt server`, I forget which.

**Comment by patilms16** [comment]
I tried these commands as well but getting same error. 
I guess Its a version issue as even grunt test was working fine previously.
But not working with latest version. Please correct me if wrong.
